/* Generated by PARSEC */
/* Helpers for the Module Implementation myJunior_Other_impl */

#include "ECOA.h"
#include "myJunior_Other_impl.h"
#include "myJunior_Other_impl_helpers.h"

#include "ECOA.h"
#include "libmarx.h"

int main(int argc, char *argv[])
{
	myJunior_Other_impl__context context;

    return 0;
}
