/* Generated by PARSEC */
/* Helpers for the Module Implementation myJunior_Other_impl */

#if !defined(MYJUNIOR_OTHER_IMPL_HELPERS)
#define MYJUNIOR_OTHER_IMPL_HELPERS
#include "ECOA.h"
#include "myJunior_Other_impl.h"

#include "ECOA.h"
#include "libmarx.h"

#if defined(__cplusplus)
extern "C" {
#endif

extern const char* MYJUNIOR_OTHER_IMPL;

void myJunior_Other_impl_log_info(myJunior_Other_impl__context* context, char *msg, ...);
void myJunior_Other_impl_log(myJunior_Other_impl__context* context, char *msg, ...);



#if defined(__cplusplus)
}
#endif
#endif /* MYJUNIOR_OTHER_IMPL_HELPERS */
