/* Module Helpers Implementation for myJunior_Other_impl */

/* @file myJunior_Other_impl_helpers.c
 * This is the Module Test Container for Module myJunior_Other_impl
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by PARSEC */

#include <stdio.h>
#include <string.h>
#include <stdarg.h>

#include "ECOA.h"
#include "myJunior_Other_impl_container.h"
#include "myJunior_Other_impl_helpers.h"

#include "ECOA.h"
#include "libmarx.h"


const char* MYJUNIOR_OTHER_IMPL = "MYJUNIOR_OTHER_IMPL: ";

void myJunior_Other_impl_log_info(myJunior_Other_impl__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYJUNIOR_OTHER_IMPL, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYJUNIOR_OTHER_IMPL, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myJunior_Other_impl_container__log_info(context, log);
}

void myJunior_Other_impl_log(myJunior_Other_impl__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYJUNIOR_OTHER_IMPL, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYJUNIOR_OTHER_IMPL, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myJunior_Other_impl_container__log_debug(context, log);
}



