/* Generated by PARSEC */
/* Module Implementation myDemoMain2_AM */

#include "ECOA.h"
#include "myDemoMain2_AM.h"

#include "pingpong.h"
#include <stdarg.h>

static void print_log(myDemoMain2_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myDemoMain2_AM_container__log_trace(context, log);
}


/* Entry points for lifecycle operations */
void myDemoMain2_AM__INITIALIZE__received(myDemoMain2_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoMain2_AM__START__received(myDemoMain2_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoMain2_AM__STOP__received(myDemoMain2_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoMain2_AM__SHUTDOWN__received(myDemoMain2_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}
int f1=0;
int f2=0;
void myDemoMain2_AM__TriggerEvent_f1__received(myDemoMain2_AM__context* context)
{
  /* @TODO TODO - To be implemented */
	if(f1 < 10){
		f1++;
		//printf("TriggerEvent_f1 : %i\n",f1);
		if(f1 >=10)
			myDemoMain2_AM_container__Finish__send(context);
	}
}

void myDemoMain2_AM__TriggerEvent_f2__received(myDemoMain2_AM__context* context)
{
  /* @TODO TODO - To be implemented */
	if(f2 < 5){
		f2++;
		//printf("TriggerEvent_f2 : %i\n",f2);
		if(f2 >=5)
			myDemoMain2_AM_container__Finish__send(context);
	}
}

