/* Generated by PARSEC */
/* Module User Context Header for module myDemoSynchronizer_AM */
#if !defined(_MYDEMOSYNCHRONIZER_AM_USER_CONTEXT_H)
#define _MYDEMOSYNCHRONIZER_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoSynchronizer_AM_user_context.h
 */

#include "lib_array.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
    lib_array__array_1k* array_1k;
    lib_array__array_4k* array_4k;
    lib_array__array_16k* array_16k;
    lib_array__array_64k* array_64k;
    lib_array__array_256k* array_256k;
    lib_array__array_10m* array_10m;
    /*********** START USER-WRITTEN USER ***********/
} myDemoSynchronizer_AM_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myDemoSynchronizer_AM_warm_start_context;

#if defined(__cplusplus)
}
#endif

#endif  /* _MYDEMOSYNCHRONIZER_AM_USER_CONTEXT_H */
