/* Generated by PARSEC */
/* Module User Context Header for module myDemoPing_AM */
#if !defined(_MYDEMOPING_AM_USER_CONTEXT_H)
#define _MYDEMOPING_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPing_AM_user_context.h
 */

#include "ECOA.h"
#include "libRoot.h"
#include "libRoot__level1A.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/

    /*********** START USER-WRITTEN USER ***********/
} myDemoPing_AM_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myDemoPing_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYDEMOPING_AM_USER_CONTEXT_H */
