/* Generated by PARSEC */
/* Module Implementation myDemoServer_mod1_impl */

#include "ECOA.h"
#include "myDemoServer_mod1_impl.h"

#include "pingpong.h"
#include <stdio.h>
#include <stdio.h>
#include <stdarg.h>


static void print_log(myDemoServer_mod1_impl__context* context, const char *format, ...){
	va_list vl;
	ECOA__log log;

	va_start(vl, format);
	vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
	va_end( vl);

	myDemoServer_mod1_impl_container__log_trace(context, log);
}

/* Entry points for lifecycle operations */
void myDemoServer_mod1_impl__INITIALIZE__received(myDemoServer_mod1_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_mod1_impl__START__received(myDemoServer_mod1_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_mod1_impl__STOP__received(myDemoServer_mod1_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_mod1_impl__SHUTDOWN__received(myDemoServer_mod1_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_mod1_impl__RR_msg__request_received(myDemoServer_mod1_impl__context* context, const ECOA__uint32 ID, const pingpong__T_2D_Position* Ping_Position, const ECOA__uint32 Ping_Target)
{

	ECOA__uint32 Pong_Target= Ping_Target +1;

	print_log(context, "RR received %i (comp : %i, mod : %i)\n", Ping_Target, Ping_Position->Latitude, Ping_Position->Longitude);
	myDemoServer_mod1_impl_container__RR_msg__response_send(context, ID,  Ping_Position,  Pong_Target);

}

