/* Generated by PARSEC */
/* Module Implementation for myDemoPing_AM
Done by Florian using Jinja */

#include "ECOA.hpp"


#include "mylib.hpp"

#include <assert.h>
#include <stdio.h>
#include "ldp_mod_container_util.h"
#include <stdarg.h>
#include "myDemoPing_AM.hpp"

namespace myDemoPing_AM
{

/* Entry points for lifecycle operations */
void Module::INITIALIZE__received(){
	user.nb_pong_received = 0;

	user.sync0_response_received = 0;
	user.sync1_response_received = 0;

	user.pong_received;
	user.pong2_received;
	user.pong3_received;
}
void Module::START__received(){
	apr_sleep(200000);

    mylib::coord coord_send_sync = { .x = 6, .y = 66};
    mylib::coord* coord_send_sync_adr = &coord_send_sync;
    mylib::t1 nb_send = 13;

    mylib::coord coord_received_sync;
    mylib::t1 nb_received;

    ECOA::return_status ret;
    do{
        ret = container->RR_msg_sync0__request_sync(nb_send, coord_send_sync, nb_received, coord_received_sync);
    }while(ret.value != ECOA::return_status::OK);
     printf("ping! nb_received = %d\n",nb_received);
    if (nb_received == 679 && coord_received_sync.x == 7 && coord_received_sync.y == 67){
    	user.sync0_response_received = 1;
    }else{
	    assert(0);
    }

	do{
        ret = container->RR_msg_sync1__request_sync(nb_send, coord_send_sync, nb_received, coord_received_sync);
    }while(ret.value != ECOA::return_status::OK);
    if (nb_received == 790 && coord_received_sync.x == 8 && coord_received_sync.y == 68){
    	user.sync1_response_received = 1;
    }else{
	    assert(0);
    }
}
void Module::STOP__received(){
/* @TODO TODO - To be implemented */
}
void Module::SHUTDOWN__received(){
/* @TODO TODO - To be implemented */
}



void Module::Pong__received(  const mylib::coord& recordwithpong, const mylib::t1 nb_pong, const mylib::Test_array& arraywithpong, const mylib::Test_fixed_array& fixedarraywithpong, const mylib::Test_enum enumwithpong)
{
	if (recordwithpong.x == 31 && recordwithpong.y == 41 && nb_pong == 15){
		user.pong_received = 1;
	}
	else if (recordwithpong.x == 32 && recordwithpong.y == 42 && nb_pong == 16){
		user.pong2_received = 1;
	}
	else if (recordwithpong.x == 33 && recordwithpong.y == 43 && nb_pong == 17){
		user.pong3_received = 1;
	}
	else{
		assert(0);
	}
	user.nb_pong_received += 1;
}





int nb_tick = 0;
void Module::TriggerPingEvent__received()
{
	mylib::t1 ping_num = 14;
	mylib::coord ping_coord = { .x = 30, .y = 40};
	mylib::Test_array ping_array = { 5 , {61,62,63,64,65} };
	mylib::Test_fixed_array ping_fixedarray = {7,8,9,10,11,12,13,14,15,16,17,18};
	mylib::Test_enum ping_testenum(mylib::Test_enum::SATURDAY);

	if (nb_tick<3)
	{
		(this->container)->Ping__send(ping_coord, ping_num, ping_array, ping_fixedarray, ping_testenum);
		nb_tick += 1;
	}
	else if (user.nb_pong_received == 9 && user.pong_received == 1 && user.pong2_received ==1 && user.pong3_received == 1 && user.sync0_response_received == 1 && user.sync1_response_received == 1){
		mylib::t1 nombre_ping_to_kill = 999;
		(this->container)->Ping__send(ping_coord, nombre_ping_to_kill, ping_array, ping_fixedarray, ping_testenum);
	}
}


/* Fault Handling API , linked to another namespace (fault_handler_impl_name) */

extern "C" {

	Module* myDemoPing_AM__new_instance()
	{
		return new Module();
	}
}

} /* namespace myDemoPing_AM */
