/* Generated by PARSEC */
/* Module Implementation myDemoPing_AM2 */
#define _GNU_SOURCE
#include <unistd.h>
// OD BEGIN
#if !defined(PIKEOS_POSIX)
#include <sys/syscall.h>
#endif
// OD END
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <sched.h>
#include <stdarg.h>

#include "ECOA.h"
#include "myDemoPing_AM2.h"

#include "pingpong.h"
#include <assert.h>
#include "ldp_fifo_manager.h"
#include "ldp_structures.h"
#include "ldp_mod_container_util.h"

static void print_log(myDemoPing_AM2__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

    myDemoPing_AM2_container__log_trace(context, log);
}

static void print_deployment_info(myDemoPing_AM2__context* context, cpu_set_t cpumask, int priority, int niceness, int sched_policy){
  char string[256];

  char cpu_mask_str[4*CPU_SETSIZE];
  for(int i=0; i<4;i++){
    if(CPU_ISSET(i, &cpumask)){
      snprintf(&cpu_mask_str[i*2],4,"|%d",i);
    }else{
      sprintf(&cpu_mask_str[i*2],"| ");
    }
  }
  snprintf(string, 256, " sched_policy:%i\n priority:%i\n niceness:%i\n cpu mask: %s\n",
                      sched_policy,
                      priority,
                      niceness,
                      cpu_mask_str);
  print_log(context, "%s", string);
}
/* Entry points for lifecycle operations */
void myDemoPing_AM2__INITIALIZE__received(myDemoPing_AM2__context* context)
{
	context->user.current_nb =0;
	context->user.data_r_value=0;
	context->user.pong_nb =0;
	context->user.tick_nb =0;
}

void myDemoPing_AM2__START__received(myDemoPing_AM2__context* context)
{
  pthread_t thread=pthread_self();
// OD BEGIN
#if !defined(PIKEOS_POSIX)
  int tid = syscall(SYS_gettid);
#endif
// OD END

  cpu_set_t cpuget;
  int sched_policy = -1;
  struct sched_param sched_param;
  int niceness = -1;

  pthread_getaffinity_np(thread,
// OD BEGIN
#if !defined(PIKEOS_POSIX)
                         sizeof(cpu_set_t),
#endif
// OD END
                         &cpuget);
  pthread_getschedparam(thread, &sched_policy, &sched_param);
// OD BEGIN
#if defined(PIKEOS_POSIX)
  niceness = 0; // default value of  getpriority(PRIO_PROCESS, 
#else
  niceness = getpriority(PRIO_PROCESS, tid);
#endif
// OD END
  print_deployment_info(context,cpuget, sched_param.sched_priority, niceness, sched_policy );

  /* assert(!CPU_ISSET(1, &cpuget)); */
  /* assert(!CPU_ISSET(2, &cpuget)); */
  /* assert(!CPU_ISSET(0, &cpuget)); */
  /* assert(CPU_ISSET(3, &cpuget)); */

  /* assert(sched_policy == SCHED_BATCH); */
  /* if(geteuid() == 0){ */
  /*   /\*root *\/ */
  /*   assert(sched_param.sched_priority == 0); */
  /*   assert(niceness != 0); */
  /* } else { */
  /*   assert(sched_param.sched_priority == 0); */
  /*   assert(niceness == 0); */
  /* } */
}

void myDemoPing_AM2__STOP__received(myDemoPing_AM2__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM2__SHUTDOWN__received(myDemoPing_AM2__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM2__Pong__received(myDemoPing_AM2__context* context, const ECOA__uint32 nb_msg)
{
	// Pong should arrived before triggerEvent
	assert(nb_msg == context->user.current_nb);
	context->user.pong_nb++;

	// But should be poped after triggerEvent arrived in FIFO
	// => check current number of activating operation if FIFO
	if(((ldp_module_context*)context->platform_hook)->fifo_manager->activating_op_num <= 0){
		printf("ERROR : no activating operations in FIFO (event)\n");
	}
}

bool first_tick2=true;
void myDemoPing_AM2__TriggerEvent__received(myDemoPing_AM2__context* context)
{
	if( ! first_tick2){
		context->user.tick_nb++;

		//check received all pong
		assert(context->user.pong_nb == 6);
		context->user.pong_nb = 0;

		// recieved update
		assert(context->user.data_r_value == context->user.tick_nb);

		context->user.current_nb++;
	}
	ECOA__uint32 ID;
	first_tick2 = false;
	myDemoPing_AM2_container__Ping_ASync__request_async(context, &ID);
	myDemoPing_AM2_container__Ping__send(context, context->user.current_nb);
	myDemoPing_AM2_container__Ping__send(context, context->user.current_nb);
	myDemoPing_AM2_container__Ping__send(context, context->user.current_nb);
	myDemoPing_AM2_container__Ping__send(context, context->user.current_nb);
	myDemoPing_AM2_container__Ping__send(context, context->user.current_nb);
	myDemoPing_AM2_container__Ping__send(context, context->user.current_nb);

}

void myDemoPing_AM2__data_r__updated(myDemoPing_AM2__context* context){
	myDemoPing_AM2_container__data_r_handle data_handle;
	int ret=myDemoPing_AM2_container__data_r__get_read_access(context, &data_handle);
	assert(ret == LDP_SUCCESS);
	memcpy(&context->user.data_r_value, data_handle.data, sizeof(ECOA__uint32) );
	ret=myDemoPing_AM2_container__data_r__release_read_access(context, &data_handle);
	assert(ret == LDP_SUCCESS);

	// But should be poped after triggerEvent arrived in FIFO
	// => check current number of activating operation if FIFO
	if(((ldp_module_context*)context->platform_hook)->fifo_manager->activating_op_num <= 0){
		printf("ERROR : no activating operations in FIFO (VD notif)\n");
	}
}

void myDemoPing_AM2__Ping_ASync__response_received(myDemoPing_AM2__context* context, const ECOA__uint32 ID, const ECOA__return_status status)
{
	assert(status == ECOA__return_status_OK);
}
