/* Generated by PARSEC */
/* Module Implementation myDemoMessageReceiver_AM */

#include "ECOA.h"
#include "myDemoMessageReceiver_AM.h"

#include "lib_array.h"
#include <assert.h>

#define SEQUENCE_SIZE 26
static char sequence[] = "abcdefghijklmnopqrstuvwxyz";

static int check_array_integrity(char* dest, unsigned int dest_size, char* src, unsigned int src_size){
	unsigned int i;
	int no_error=1;
	for(i=0;i<dest_size && no_error;i++){
		if(dest[i] != src[i%src_size]){
			no_error=0;
		}
	}
	return no_error;
}


/* Entry points for lifecycle operations */
void myDemoMessageReceiver_AM__INITIALIZE__received(myDemoMessageReceiver_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoMessageReceiver_AM__START__received(myDemoMessageReceiver_AM__context* context)
{
	context->user._256k_received_count=0;
  context->user._10m_received_count=0;
  context->user._64k_received_count=0;
  context->user._16k_received_count=0;
  context->user._1k_received_count=0;
  context->user._4k_received_count=0;
}

void myDemoMessageReceiver_AM__STOP__received(myDemoMessageReceiver_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoMessageReceiver_AM__SHUTDOWN__received(myDemoMessageReceiver_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

static void check_finish_and_send_finish(myDemoMessageReceiver_AM__context* context) {

  if (context->user._256k_received_count==10 &&
      context->user._10m_received_count==10 &&
      context->user._64k_received_count==10 &&
      context->user._16k_received_count==10 &&
      context->user._1k_received_count==10 &&
      context->user._4k_received_count==10)
      {
        myDemoMessageReceiver_AM_container__Finish_sent__send(context);
      }
}

void myDemoMessageReceiver_AM__Msg_array_256k__received(myDemoMessageReceiver_AM__context* context, const lib_array__array_256k* array)
{
	int ret=check_array_integrity((char*) array, lib_array__array_256k_MAXSIZE, sequence, SEQUENCE_SIZE);
  assert(ret == 1);
  context->user._256k_received_count++;
  check_finish_and_send_finish(context);
}

void myDemoMessageReceiver_AM__Msg_array_10m__received(myDemoMessageReceiver_AM__context* context, const lib_array__array_10m* array)
{
  int ret=check_array_integrity((char*) array, lib_array__array_10m_MAXSIZE, sequence, SEQUENCE_SIZE);
	assert(ret == 1);
  context->user._10m_received_count++;
  check_finish_and_send_finish(context);
}

void myDemoMessageReceiver_AM__Msg_array_64k__received(myDemoMessageReceiver_AM__context* context, const lib_array__array_64k* array)
{
  int ret=check_array_integrity((char*) array, lib_array__array_64k_MAXSIZE, sequence, SEQUENCE_SIZE);
	assert(ret == 1);
  context->user._64k_received_count++;
  check_finish_and_send_finish(context);
}

void myDemoMessageReceiver_AM__Msg_array_16k__received(myDemoMessageReceiver_AM__context* context, const lib_array__array_16k* array)
{
  int ret=check_array_integrity((char*) array, lib_array__array_16k_MAXSIZE, sequence, SEQUENCE_SIZE);
	assert(ret == 1);
  context->user._16k_received_count++;
  check_finish_and_send_finish(context);
}

void myDemoMessageReceiver_AM__Msg_array_1k__received(myDemoMessageReceiver_AM__context* context, const lib_array__array_1k* array)
{
  int ret=check_array_integrity((char*) array, lib_array__array_1k_MAXSIZE, sequence, SEQUENCE_SIZE);
	assert(ret == 1);
  context->user._1k_received_count++;
  check_finish_and_send_finish(context);
}

void myDemoMessageReceiver_AM__Msg_array_4k__received(myDemoMessageReceiver_AM__context* context, const lib_array__array_4k* array)
{
  int ret=check_array_integrity((char*) array, lib_array__array_4k_MAXSIZE, sequence, SEQUENCE_SIZE);
	assert(ret == 1);
  context->user._4k_received_count++;
  check_finish_and_send_finish(context);
}
