/* Generated by PARSEC */
/* Module Implementation myEarth_mod_impl */

#include "ECOA.h"
#include "myLib.h"
#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
#include "ldp_mod_container_util.h"
#include "myEarth_mod_impl.h"

static void print_log(myEarth_mod_impl__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myEarth_mod_impl_container__log_trace(context, log);
}

/* Entry points for lifecycle operations */
void myEarth_mod_impl__INITIALIZE__received(myEarth_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myEarth_mod_impl__START__received(myEarth_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myEarth_mod_impl__STOP__received(myEarth_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myEarth_mod_impl__SHUTDOWN__received(myEarth_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

int tick_num = 0;
void myEarth_mod_impl__trigger__received(myEarth_mod_impl__context* context)
{
    ECOA__uint32 ID;
    assert(myEarth_mod_impl_container__satellite_0_position__request_async(context, &ID)==ECOA__return_status_OK);
    assert(myEarth_mod_impl_container__satellite_1_position__request_async(context, &ID)==ECOA__return_status_OK);
    assert(myEarth_mod_impl_container__satellite_2_position__request_async(context, &ID)==ECOA__return_status_OK);
    assert(myEarth_mod_impl_container__satellite_3_position__request_async(context, &ID)==ECOA__return_status_OK);
    tick_num++;

    if (tick_num > 3){
        print_log(context, "\033[1;32m SUCCESS  \033[0m");
        ldp_kill_platform((ldp_module_context*)context->platform_hook);
    }
}

void myEarth_mod_impl__data__received(myEarth_mod_impl__context* context, const myLib__array_data* data, const ECOA__uint32 satellite_num)
{
    print_log(context, "Earth received data form satellite %i", satellite_num);
    for(int i=0; i<myLib__array_data_MAXSIZE; i++){
        assert((*data)[i] == satellite_num + i);
    }

}

static void satillite_position_received(myEarth_mod_impl__context* context,
                                        const ECOA__return_status status,
                                        const myLib__position* data,
                                        const ECOA__uint32 satellite_num){
    assert(status == ECOA__return_status_OK);
    assert(data->x == satellite_num);
    assert(data->y == 1);
    assert(data->z == 2);
    print_log(context, "Earth received position form satellite %i", satellite_num);
}


void myEarth_mod_impl__satellite_0_position__response_received(myEarth_mod_impl__context* context, const ECOA__uint32 ID, const ECOA__return_status status, const myLib__position* data, const ECOA__uint32 satellite_num)
{
    satillite_position_received(context,status, data, satellite_num);
}
void myEarth_mod_impl__satellite_1_position__response_received(myEarth_mod_impl__context* context, const ECOA__uint32 ID, const ECOA__return_status status, const myLib__position* data, const ECOA__uint32 satellite_num)
{
    satillite_position_received(context,status, data, satellite_num);
}

void myEarth_mod_impl__satellite_2_position__response_received(myEarth_mod_impl__context* context, const ECOA__uint32 ID, const ECOA__return_status status, const myLib__position* data, const ECOA__uint32 satellite_num)
{
    satillite_position_received(context,status, data, satellite_num);
}
void myEarth_mod_impl__satellite_3_position__response_received(myEarth_mod_impl__context* context, const ECOA__uint32 ID, const ECOA__return_status status, const myLib__position* data, const ECOA__uint32 satellite_num)
{
    satillite_position_received(context,status, data, satellite_num);
}



