/* Generated by PARSEC */
/* Module User Context Header for module myDemoPing_AM */
#if !defined(__MYDEMOPING_AM_USER_CONTEXT_H__)
#define __MYDEMOPING_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPing_AM_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/

  /*********** USER ***********/
} myDemoPing_AM_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myDemoPing_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYDEMOPING_AM_USER_CONTEXT_H__ */
