/* Generated by PARSEC */
/* Module Implementation myCompWriter_mod0 */

#include "ECOA.h"
#include "myCompWriter_mod0.h"

#include "VD_lib.h"
#include <assert.h>

/* Entry points for lifecycle operations */
void myCompWriter_mod0__INITIALIZE__received(myCompWriter_mod0__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod0__START__received(myCompWriter_mod0__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod0__STOP__received(myCompWriter_mod0__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod0__SHUTDOWN__received(myCompWriter_mod0__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod0__tick__received(myCompWriter_mod0__context* context)
{
ECOA__return_status ret;
myCompWriter_mod0_container__write_vector_handle data_handle;
ret = myCompWriter_mod0_container__write_vector__get_write_access(context, &data_handle);
if (ret == ECOA__return_status_OK || ret == ECOA__return_status_DATA_NOT_INITIALIZED){
	VD_lib__vector_data* vector = data_handle.data;


	if(ret == ECOA__return_status_DATA_NOT_INITIALIZED){
		vector->nb_y = 30;
		vector->nb_x = 0;
		myCompWriter_mod0_container__get_writer_id_value(context, &vector->writer_id);
	}

	if (vector->nb_x > vector->nb_y){
		ret = myCompWriter_mod0_container__write_vector__cancel_write_access(context, &data_handle);
		assert(ret == ECOA__return_status_OK);
	}else{
		vector->nb_x += 1;
		ret = myCompWriter_mod0_container__write_vector__publish_write_access(context, &data_handle);
		assert(ret == ECOA__return_status_OK);

		if( vector->nb_x == vector->nb_y){
			myCompWriter_mod0_container__finish__send(context);
		}
	}
}

}

