/* Generated by PARSEC */
/* Module Implementation myCompWritter_mod */

#include "ECOA.h"
#include "myCompWritter_mod.h"

#include "VD_lib.h"
#include <string.h>
#include "assert.h"
/* Entry points for lifecycle operations */
void myCompWritter_mod__INITIALIZE__received(myCompWritter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWritter_mod__START__received(myCompWritter_mod__context* context)
{

	myCompWritter_mod_container__get_mod_id_value(context, &(context->user.mod_id));
	myCompWritter_mod_container__written_vector_handle data_handle;
	int ret = myCompWritter_mod_container__written_vector__get_write_access(context, &data_handle);
	assert(ret == ECOA__return_status_DATA_NOT_INITIALIZED);

	if (context->user.mod_id == 0){
		data_handle.data->nb_x = 1;
	}else{
		data_handle.data->nb_y = 1;
	}
	memcpy(&context->user.saved_vector, data_handle.data, sizeof(VD_lib__vector_data));

	ret = myCompWritter_mod_container__written_vector__publish_write_access(context, &data_handle);
	assert(ret == ECOA__return_status_OK);
}

void myCompWritter_mod__STOP__received(myCompWritter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWritter_mod__SHUTDOWN__received(myCompWritter_mod__context* context)
{

}


void myCompWritter_mod__trigger__received(myCompWritter_mod__context* context){
	myCompWritter_mod_container__written_vector_handle data_handle;
	int ret = myCompWritter_mod_container__written_vector__get_write_access(context, &data_handle);
	assert(ret == ECOA__return_status_OK);

	// check and update vector
	if (context->user.mod_id == 0){
		assert(data_handle.data->nb_x == context->user.saved_vector.nb_x);
		data_handle.data->nb_x++;
	}else{
		assert(data_handle.data->nb_y == context->user.saved_vector.nb_y);
		data_handle.data->nb_y++;
	}

	// save vector
	memcpy(&context->user.saved_vector, data_handle.data, sizeof(VD_lib__vector_data));
	ret = myCompWritter_mod_container__written_vector__publish_write_access(context, &data_handle);
	assert(ret == ECOA__return_status_OK);
}

