/* Generated by PARSEC */
/* Module Implementation myDemoPong_AM */
#define _GNU_SOURCE
#include <unistd.h>
// OD BEGIN
#if !defined(PIKEOS_POSIX)
#include <sys/syscall.h>
#endif
// OD END
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <sched.h>
#include <stdarg.h>

#include "ECOA.h"
#include "myDemoPong_AM.h"

#include "pingpong.h"
#include <assert.h>
#include "ldp_fifo_manager.h"
#include "ldp_structures.h"

static void print_log(myDemoPong_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

    myDemoPong_AM_container__log_trace(context, log);
}

static void print_deployment_info(myDemoPong_AM__context* context, cpu_set_t cpumask, int priority, int niceness, int sched_policy){
  char string[256];

  char cpu_mask_str[4*CPU_SETSIZE];
  for(int i=0; i<4;i++){
    if(CPU_ISSET(i, &cpumask)){
      snprintf(&cpu_mask_str[i*2],4,"|%d",i);
    }else{
      sprintf(&cpu_mask_str[i*2],"| ");
    }
  }
  snprintf(string, 256, " sched_policy:%i\n priority:%i\n niceness:%i\n cpu mask: %s\n",
                      sched_policy,
                      priority,
                      niceness,
                      cpu_mask_str);
  print_log(context, "%s", string);
}

/* Entry points for lifecycle operations */
void myDemoPong_AM__INITIALIZE__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__START__received(myDemoPong_AM__context* context)
{
  pthread_t thread=pthread_self();
// OD BEGIN
#if !defined(PIKEOS_POSIX)
  int tid = syscall(SYS_gettid);
#endif
// OD END

  cpu_set_t cpuget;
  int sched_policy = -1;
  struct sched_param sched_param;
  int niceness = -1;

  pthread_getaffinity_np(thread,
// OD BEGIN
#if !defined(PIKEOS_POSIX)
                         sizeof(cpu_set_t),
#endif
// OD END
                         &cpuget);
  pthread_getschedparam(thread, &sched_policy, &sched_param);
// OD BEGIN
#if defined(PIKEOS_POSIX)
  niceness = 0; // default value of  getpriority(PRIO_PROCESS, 
#else
  niceness = getpriority(PRIO_PROCESS, tid);
#endif
// OD END
  print_deployment_info(context,cpuget, sched_param.sched_priority, niceness, sched_policy );

  /* assert(!CPU_ISSET(1, &cpuget)); */
  /* assert(!CPU_ISSET(2, &cpuget)); */
  /* assert(!CPU_ISSET(0, &cpuget)); */
  /* assert(CPU_ISSET(3, &cpuget)); */

  /* assert(sched_policy == SCHED_BATCH); */
  /* if(geteuid() == 0){ */
  /*   /\*root *\/ */
  /*   assert(sched_param.sched_priority == 0); */
  /*   assert(niceness != 0); */
  /* } else { */
  /*   assert(sched_param.sched_priority == 0); */
  /*   assert(niceness == 0); */
  /* } */
}

void myDemoPong_AM__STOP__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__SHUTDOWN__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

int counter_pong2 = 0;
void myDemoPong_AM__Ping__received(myDemoPong_AM__context* context, const ECOA__uint32 nb_msg)
{	counter_pong2++;
	myDemoPong_AM_container__Pong__send(context, nb_msg);

	// only the first time
	if ( (counter_pong2 % 6) == 0){
		myDemoPong_AM_container__data_w_handle data_handle;
		ECOA__uint32 data_value;
		if(myDemoPong_AM_container__data_w__get_write_access(context, &data_handle) == ECOA__return_status_DATA_NOT_INITIALIZED){
			data_value = 1;
		}else{
			memcpy(&data_value,data_handle.data,sizeof(ECOA__uint32));
			data_value +=1;
		}
		memcpy(data_handle.data, &data_value, sizeof(ECOA__uint32));
		int ret=myDemoPong_AM_container__data_w__publish_write_access(context, &data_handle);
		assert(ret == ECOA__return_status_OK);
	}
}

void myDemoPong_AM__Ping_RR__request_received(myDemoPong_AM__context* context, const ECOA__uint32 ID)
{
	// RR must arrived before all ping
	if(((ldp_module_context*)context->platform_hook)->fifo_manager->activating_op_num <= 0){
		printf("ERROR : no activating operations in FIFO (RR received)\n");
	}
	myDemoPong_AM_container__Ping_RR__response_send(context, ID);
}
