set ( APR_ROOT_PATH ${APR_DIR} CACHE STRING "APR install path")
set ( log4cplus_ROOT_PATH ${LOG4CPLUS_DIR} CACHE PATH "log4cplus install dir")
set ( CUNIT_ROOT_PATH ${CUNIT_DIR} CACHE PATH "CUnit install dir")
set ( ZLOG_ROOT_PATH ${ZLOG_DIR} CACHE PATH "zlog install dir")
set ( LDP_LOG_USE "log4cplus" CACHE STRING "Use log4cplus, zlog or console for logging")
set ( LDP_LINK_TYPE SHARED CACHE STRING "Use STATIC or SHARED link type")
set ( CMAKE_BUILD_TYPE Debug CACHE STRING "build type")
set ( USER_CMAKE_C_FLAGS "-Wall -std=c99" CACHE STRING "user compilation flag")
set ( USER_CMAKE_CXX_FLAGS "-Wall -std=gnu++11" CACHE STRING "user compilation flag")
set ( CMAKE_USE_UDP_PROTO false CACHE BOOL "UDP or TCP protocol")
set ( CMAKE_USE_AF_UNIX false CACHE BOOL "AF_INET or AF_UNIX socket family")
