/* Generated by PARSEC */
/* Module Implementation myDemoPong_AM */

#include "ECOA.h"

#include "pingpong.h"
#include <stdarg.h>
#include <stdio.h>
#include "ldp_mod_container_util.h"
#include "myDemoPong_AM.h"

static void print_log(myDemoPong_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myDemoPong_AM_container__log_trace(context, log);
}

/* Entry points for lifecycle operations */
void myDemoPong_AM__INITIALIZE__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__START__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__STOP__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__SHUTDOWN__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

pongcount=0;
void myDemoPong_AM__Ping__received(myDemoPong_AM__context* context)
{
  if (pongcount<3) {//print_log(context, "Ping received. Send Pong");
	myDemoPong_AM_container__Pong__send(context);
	pongcount++;
  }
  else {
  	  print_log(context, "\033[1;32m SUCCESS  \033[0m");
	  fflush(stdout);
	  ldp_kill_platform((ldp_module_context*)context->platform_hook);
  }
}
