/* Generated by PARSEC */
/* Module Implementation myCompWriter_mod */

#include "ECOA.h"
#include "myCompWriter_mod.h"

#include "VD_lib.h"

#include <string.h>
#include <assert.h>
#include <unistd.h>
#include <stdio.h>

/* Entry points for lifecycle operations */
#include <stdarg.h>
static void print_log(myCompWriter_mod__context* context, const char *format, ...){
va_list vl;
ECOA__log log;
va_start(vl, format);
vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
va_end( vl);

myCompWriter_mod_container__log_trace(context, log);
}

void myCompWriter_mod__INITIALIZE__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod__REINITIALIZE__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod__START__received(myCompWriter_mod__context* context)
{
  VD_lib__vector_data new_vector={0,0};
  VD_lib__vector_data old_vector={0,0};
  myCompWriter_mod_container__write_vector_handle handle;

  while(1){
  	ECOA__return_status ret = myCompWriter_mod_container__write_vector__get_write_access(context, &handle);
  	if(ret == ECOA__return_status_DATA_NOT_INITIALIZED){
  		// first write
  		print_log(context,"first write");
  		new_vector.nb_x = -33;
  		new_vector.nb_y = 33;
  	}else{
  		assert(ret == ECOA__return_status_OK);

      	memcpy(&new_vector,handle.data,sizeof(VD_lib__vector_data) );
  		assert( new_vector.nb_x == old_vector.nb_x);
  		assert( new_vector.nb_y == old_vector.nb_y);

  		new_vector.nb_x++;
  		new_vector.nb_y--;
  	}

  	memcpy(handle.data, &new_vector,sizeof(VD_lib__vector_data) );
  	old_vector = new_vector;

	ret=myCompWriter_mod_container__write_vector__publish_write_access(context, &handle);
	assert(ret == ECOA__return_status_OK);

	if(new_vector.nb_x == new_vector.nb_y)
		break;

  	usleep(40000);
  }
  print_log(context,"writer finish");
  myCompWriter_mod_container__finish__send(context);
  assert(1);
}

void myCompWriter_mod__STOP__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod__SHUTDOWN__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

