/* Generated by PARSEC */
/* Module User Context Header for module myDemoPing_AM */
#if !defined(_MYDEMOPING_AM_USER_CONTEXT_H)
#define _MYDEMOPING_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPing_AM_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
    char test_name[12];
    ECOA__uint32 current_nb;
    ECOA__uint32 pong_nb;
    ECOA__uint32 data_r_value;
    ECOA__uint32 RR_answer_nb;
    ECOA__uint32 tick_nb;
    ECOA__uint32 dyn_trig_value;
    ECOA__uint32 activating_error_num; // number of error in
                                     // activating/non-avtivating operation
  /*********** START USER-WRITTEN USER ***********/
} myDemoPing_AM_user_context;

#if defined(__cplusplus)
}
#endif

#endif  /* _MYDEMOPING_AM_USER_CONTEXT_H */
