/* Generated by PARSEC */
/* Module User Context Header for module myDummy_mod_impl */
#if !defined(_MYDUMMY_MOD_IMPL_USER_CONTEXT_H)
#define _MYDUMMY_MOD_IMPL_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDummy_mod_impl_user_context.h
 */

#include "ECOA.h"
#include "lib_module.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/

    /*********** START USER-WRITTEN USER ***********/
} myDummy_mod_impl_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myDummy_mod_impl_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYDUMMY_MOD_IMPL_USER_CONTEXT_H */
