/* Generated by PARSEC */
/* Module User Context Header for module myDemoPing_AM */
#if !defined(_MYDEMOPING_AM_USER_CONTEXT_H)
#define _MYDEMOPING_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPing_AM_user_context.h
 */

#include "pingpong.h"

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYDEMOPING_AM_USER_CONTEXT_H */
