/* Generated by PARSEC */
/* Module User Context Header for module myDemoEmitter_AM */
#if !defined(_MYDEMOEMITTER_AM_USER_CONTEXT_H)
#define _MYDEMOEMITTER_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoEmitter_AM_user_context.h
 */

#include "ECOA.h"
#include "lib_module.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/

    /*********** START USER-WRITTEN USER ***********/
} myDemoEmitter_AM_user_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYDEMOEMITTER_AM_USER_CONTEXT_H */
