/* Generated by PARSEC */
/* Module Implementation myCompReader_mod */

#include "ECOA.h"
#include "myCompReader_mod.h"

#include "VD_lib.h"
#include <stdio.h>
#include <assert.h>

/* Entry points for lifecycle operations */
#include <stdarg.h>
static void print_log(myCompReader_mod__context* context, const char *format, ...){
va_list vl;
ECOA__log log;
va_start(vl, format);
vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
va_end( vl);

myCompReader_mod_container__log_trace(context, log);
}

void myCompReader_mod__INITIALIZE__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod__REINITIALIZE__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod__START__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod__STOP__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod__SHUTDOWN__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}
void myCompReader_mod__read_vector00__updated(myCompReader_mod__context* context){
  myCompReader_mod_container__read_vector00_handle data_type;
  ECOA__return_status ret = myCompReader_mod_container__read_vector00__get_read_access(context, &data_type);
  assert(ret == ECOA__return_status_OK);

  VD_lib__vector_data* new_vector=data_type.data;
  assert(new_vector->writer_id == 0x10);

  print_log(context,"DATA updated version 00 %i %i\n",new_vector->nb_x, new_vector->nb_y);
  // assert(new_vector->version_nb == 0);
  if(new_vector->nb_x == new_vector->nb_y){
    print_log(context,"reader version 0 finish");
    myCompReader_mod_container__finish__send(context);
    assert(1);
  }
  ret = myCompReader_mod_container__read_vector00__release_read_access(context, &data_type);
  assert(ret == ECOA__return_status_OK);
}

void myCompReader_mod__read_vector0__updated(myCompReader_mod__context* context){
  myCompReader_mod_container__read_vector0_handle data_type;
  ECOA__return_status ret = myCompReader_mod_container__read_vector0__get_read_access(context, &data_type);
  assert(ret == ECOA__return_status_OK);

  VD_lib__vector_data* new_vector=data_type.data;
  assert(new_vector->writer_id == 0x10);

  print_log(context,"DATA updated version 0 %i %i\n",new_vector->nb_x, new_vector->nb_y);
  // assert(new_vector->version_nb == 0);
  if(new_vector->nb_x == new_vector->nb_y){
    print_log(context,"reader version 0 finish");
    myCompReader_mod_container__finish__send(context);
    assert(1);
  }
  ret = myCompReader_mod_container__read_vector0__release_read_access(context, &data_type);
  assert(ret == ECOA__return_status_OK);
}

void myCompReader_mod__read_vector1__updated(myCompReader_mod__context* context){
  myCompReader_mod_container__read_vector1_handle data_type;
  ECOA__return_status ret = myCompReader_mod_container__read_vector1__get_read_access(context, &data_type);
  assert(ret == ECOA__return_status_OK);

  VD_lib__vector_data* new_vector=data_type.data;
  assert(new_vector->writer_id == 0x11);

  print_log(context,"DATA updated version 1 %i %i\n",new_vector->nb_x, new_vector->nb_y);
  //assert(new_vector->version_nb == 1);
  if(new_vector->nb_x == new_vector->nb_y){
    print_log(context,"reader version 0 finish");
    myCompReader_mod_container__finish__send(context);
    assert(1);
  }
  ret = myCompReader_mod_container__read_vector1__release_read_access(context, &data_type);
  assert(ret == ECOA__return_status_OK);
}



void myCompReader_mod__read_vector2__updated(myCompReader_mod__context* context){
  myCompReader_mod_container__read_vector2_handle data_type;
  ECOA__return_status ret = myCompReader_mod_container__read_vector2__get_read_access(context, &data_type);
  assert(ret == ECOA__return_status_OK);

  VD_lib__vector_data* new_vector=data_type.data;
  assert(new_vector->writer_id == 0x12);

  print_log(context,"DATA updated version 2 %i %i\n",new_vector->nb_x, new_vector->nb_y);
  //assert(new_vector->version_nb == 1);
  if(new_vector->nb_x == new_vector->nb_y){
    print_log(context,"reader version 2 finish");
    myCompReader_mod_container__finish__send(context);
    assert(1);
  }
  ret = myCompReader_mod_container__read_vector2__release_read_access(context, &data_type);
  assert(ret == ECOA__return_status_OK);
}

