/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.0.0    
*                date: 2022-04-01 10:48:02.047975    
*/


/* Module Implementation myJunior_Main_impl */

#include "ECOA.h"
#include "myJunior_Main_impl.h"

#include "ECOA.h"
#include "libmarx.h"

#include <string.h>
#include <stdio.h>
#include <stdarg.h>

#include <pthread.h>
#include <unistd.h>
#include <myJunior_External_Interface.h>

#define MTRACE    0
#define MDEBUG    1
#define MINFO     2
#define MWARNING  3

void
myJunior_Main_impl__log (myJunior_Main_impl__context * context, int level, char *msg, ...)
{
  ECOA__log log;
  va_list argp;

  va_start (argp, msg);
  vsnprintf ((char *) &log.data, ECOA__LOG_MAXSIZE, msg, argp);
  va_end (argp);
  log.current_size = strnlen ((char *) &log.data, ECOA__LOG_MAXSIZE);
  switch (level)
    {
    case MTRACE:
      myJunior_Main_impl_container__log_trace (context, log);
      break;
    case MDEBUG:
      myJunior_Main_impl_container__log_debug (context, log);
      break;
    case MINFO:
      myJunior_Main_impl_container__log_info (context, log);
      break;
    case MWARNING:
      myJunior_Main_impl_container__log_warning (context, log);
      break;
    default:
      myJunior_Main_impl_container__log_trace (context, log);
    }
}



static void *
c_thread_function (void *p_data)
{
  while (1)
    {
      sleep (1);
      myJunior__FeedbackLegacy (126);
    }
  return NULL;
}




/*
 * Entry points for lifecycle operations 
 */
void
myJunior_Main_impl__INITIALIZE__received (myJunior_Main_impl__context * context)
{
  int result = 0;

  result = pthread_create (&context->user.thread_handle, NULL, c_thread_function, NULL);
  if (result != 0)
    {
      myJunior_Main_impl__log (context, MWARNING, "Error when creating the thread (%s)", strerror (result));
    }
}

void
myJunior_Main_impl__START__received (myJunior_Main_impl__context * context)
{
  /*
   * @TODO TODO - To be implemented 
   */
}

void
myJunior_Main_impl__STOP__received (myJunior_Main_impl__context * context)
{
  /*
   * @TODO TODO - To be implemented 
   */
}

void
myJunior_Main_impl__SHUTDOWN__received (myJunior_Main_impl__context * context)
{
  pthread_join (context->user.thread_handle, NULL);
}


void
myJunior_Main_impl__TheFeedback__received (myJunior_Main_impl__context * context, const ECOA__uint32 param)
{
  myJunior_Main_impl__log (context, MTRACE, "External Feedback from legacy code %d", param);
}


void
myJunior_Main_impl__command__received (myJunior_Main_impl__context * context, const libmarx__T_Data * param)
{
  ECOA__return_status status;
  myJunior_Main_impl_container__information_handle data_handle;

  if (param->F_ID == 42)
    {
      context->user.data_1 = *param;
      context->user.data_1.F_Counter++;
      myJunior_Main_impl_container__notification__send (context, &context->user.data_1);
    }
  else if (param->F_ID == 84)
    {
      context->user.data_2 = *param;
      context->user.data_2.F_Counter++;
      myJunior_Main_impl_container__notification__send (context, &context->user.data_2);
    }
  else
    {
      myJunior_Main_impl__log (context, MWARNING, "Command from an unknown elder %d", param->F_ID);
    }

  status = myJunior_Main_impl_container__information__get_write_access (context, &data_handle);
  if (status == ECOA__return_status_OK || status == ECOA__return_status_DATA_NOT_INITIALIZED)
    {
      if (param->F_ID == 42)
        {
          data_handle.data->F_ID = context->user.data_1.F_ID;
          data_handle.data->F_Counter = context->user.data_1.F_Counter;
          data_handle.data->F_Angle = context->user.data_1.F_Angle;
        }
      else if (param->F_ID == 84)
        {
          data_handle.data->F_ID = context->user.data_2.F_ID;
          data_handle.data->F_Counter = context->user.data_2.F_Counter;
          data_handle.data->F_Angle = context->user.data_2.F_Angle;
        }
      status = myJunior_Main_impl_container__information__publish_write_access (context, &data_handle);
      if (status != ECOA__return_status_OK)
        {
          myJunior_Main_impl__log (context, MWARNING, "Error when publishing data from junior %d", param->F_ID);
        }
    }
  else
    {
      status = myJunior_Main_impl_container__information__cancel_write_access (context, &data_handle);
      if (status != ECOA__return_status_OK)
        {
          myJunior_Main_impl__log (context, MWARNING, "Error when cancelling data access from junior %d", param->F_ID);
        }
    }
}


void
myJunior_Main_impl__internal_report__received (myJunior_Main_impl__context * context, const libmarx__T_Test_Report * param)
{
}


void
myJunior_Main_impl__transaction__request_received (myJunior_Main_impl__context * context, const ECOA__uint32 ID,
                                                   const libmarx__T_Data * input)
{
  ECOA__return_status status = ECOA__return_status_OK;

  if (input->F_ID == 42)
    {
      status = myJunior_Main_impl_container__transaction__response_send (context, ID, &context->user.data_1);
    }
  else if (input->F_ID == 84)
    {
      status = myJunior_Main_impl_container__transaction__response_send (context, ID, &context->user.data_2);
    }
  else
    {
      myJunior_Main_impl__log (context, MWARNING, "Transaction from an unknown elder %d", input->F_ID);
      status = myJunior_Main_impl_container__transaction__response_send (context, ID, &context->user.data_1);
    }

  if (status != ECOA__return_status_OK)
    {
      myJunior_Main_impl__log (context, MWARNING, "Error with response_send from Junior %d", input->F_ID);
    }

}
