/* Generated by PARSEC */
/* Module Implementation myDemoPong_AM */

#include "ECOA.h"

#include "lib.h"
#include "ldp_mod_container_util.h"
#include <assert.h>
#include <string.h>
#include "myDemoPong_AM.h"


/* Entry points for lifecycle operations */
void myDemoPong_AM__INITIALIZE__received(myDemoPong_AM__context* context)
{
  context->user.ping_received = 0;
}

void myDemoPong_AM__REINITIALIZE__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__START__received(myDemoPong_AM__context* context)
{
  // check constant property
  ECOA__uint16 cst_value;
  myDemoPong_AM_container__get_p_constant_value(context, &cst_value);
  assert(cst_value == lib__magic_number);

  // check enum property
  lib__Test_enum enum_val;
  myDemoPong_AM_container__get_p_enum_value(context, &enum_val);
  assert(enum_val == lib__Test_enum_SATURDAY);

  // check fixed array property
  lib__Test_fixed_array fixed_array_val;
  myDemoPong_AM_container__get_p_fixed_array_value(context, &fixed_array_val );
  for (int i=0; i<10; i++){
    if (i != 9){
      assert(fixed_array_val[i] == i);
    }else{
      assert(fixed_array_val[i] == lib__magic_number);
    }
  }

  // check array property
  lib__Test_array array_val;
  myDemoPong_AM_container__get_p_array_value(context, &array_val);
  assert(array_val.current_size == 3);
  for(int i=0; i<array_val.current_size;i++){
    assert(array_val.data[i]=i+1);
  }

  // check fixed complex array
  lib__Test_fixed_array f_array_compl_val;
  myDemoPong_AM_container__get_p_fixed_array_complex_value(context, &f_array_compl_val );
  lib__Test_fixed_array f_array_compl_val2 = {0,1,2,777,777,777,777,777,9,lib__magic_number};
  for(int i=0; i<10;i++)
    assert(f_array_compl_val[i] == f_array_compl_val2[i]);

  // check matrix
  lib__Test_matrix_fixed_array maxtrix_val;
  myDemoPong_AM_container__get_p_fixed_array_matrix_value(context, &maxtrix_val);
  lib__Test_fixed_array tmp2 = {1,4,4,4,4,3,3,3,0,0};
  for(int i=0; i<10;i++)
    assert(maxtrix_val[0][i] == tmp2[i]);

  for (int i=1; i<lib__Test_matrix_fixed_array_MAXSIZE; i++){
    assert(maxtrix_val[i][0] == 5);
    for (int j=1; j<lib__Test_fixed_array_MAXSIZE; j++){
      assert(maxtrix_val[i][j]=1);
    }
  }

  // check enum array
  lib__Test_enum_array enume_array_val;
  myDemoPong_AM_container__get_p_enum_array_value(context, & enume_array_val);
  lib__Test_enum_array enume_array_tmp = {lib__Test_enum_SUNDAY, lib__Test_enum_SATURDAY,lib__Test_enum_SATURDAY , lib__Test_enum_SUNDAY, lib__Test_enum_SUNDAY};
  for (int i=1; i<lib__Test_matrix_fixed_array_MAXSIZE; i++){
    assert(enume_array_val[i] == enume_array_tmp[i]);
  }

  // check string
  lib__Test_array_char char_array_val;
  myDemoPong_AM_container__get_p_array_string_value(context, & char_array_val);
  assert(char_array_val.current_size == 8);
  assert(strncmp (char_array_val.data, "\"LDP\"A", char_array_val.current_size) == 0);

  lib__Test_fixed_array_char char_f_array_val;
  myDemoPong_AM_container__get_p_fixed_array_string_value(context, & char_f_array_val);
  assert(strncmp (char_f_array_val, "A\"LDP\"AA", lib__Test_fixed_array_char_MAXSIZE) == 0);

  // check ascii
  lib__Test_array_char array_ascii_val;
  myDemoPong_AM_container__get_p_array_ascii_value(context, &array_ascii_val);
  assert(array_ascii_val.current_size == 3);
  assert(strncmp (array_ascii_val.data, "ABC", 3) == 0);

  lib__Test_fixed_array_char f_array_ascii_val;
  myDemoPong_AM_container__get_p_fixed_array_ascii_value(context, &f_array_ascii_val);
  for ( int i=0; i< 10 ; i++){
    assert(f_array_ascii_val[i]== 0x41+i);
  }

  // check char8 matrix
  lib__Test_fixed_matrix_char fixed_matrix_ascii_val;
  myDemoPong_AM_container__get_p_fixed_matrix_ascii_value(context, &fixed_matrix_ascii_val);
  assert(strncmp (fixed_matrix_ascii_val[0], "AAAAAAAAAA", lib__Test_matrix_fixed_array_MAXSIZE) == 0);
  for(int i=1; i<lib__Test_fixed_matrix_char_MAXSIZE;i++){
    assert(strncmp (fixed_matrix_ascii_val[i], "ABCDEFGHIJ",lib__Test_matrix_fixed_array_MAXSIZE) == 0);
  }


  lib__Test_matrix_char matrix_ascii_val;
  myDemoPong_AM_container__get_p_matrix_ascii_value(context, &matrix_ascii_val);
  assert(matrix_ascii_val.current_size == 4);
  assert(matrix_ascii_val.data[0].current_size == 2);
  assert(strncmp (matrix_ascii_val.data[0].data, "AB", 2) == 0);
  assert(matrix_ascii_val.data[1].current_size == 2);
  assert(strncmp (matrix_ascii_val.data[1].data, "AB", 2) == 0);

  assert(matrix_ascii_val.data[2].current_size == 4);
  assert(strncmp (matrix_ascii_val.data[2].data, "AAAA", 4) == 0);
  assert(matrix_ascii_val.data[3].current_size == 4);
  assert(strncmp (matrix_ascii_val.data[3].data, "AAAA", 4) == 0);


}

void myDemoPong_AM__STOP__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__SHUTDOWN__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__Ping__received(myDemoPong_AM__context* context)
{
  ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
	context->user.ping_received++;
	if (context->user.ping_received == 2){
		ldp_kill_platform(ctx);
	}
}

