/* Generated by PARSEC */
/* Module User Context Header for module mydemoClient1_AM */
#if !defined(__MYDEMOCLIENT1_AM_USER_CONTEXT_H__)
#define __MYDEMOCLIENT1_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file mydemoClient1_AM_user_context.h
 */

/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/

  /*********** USER ***********/
} mydemoClient1_AM_user_context;

typedef struct
{

} mydemoClient1_AM_warm_start_context;
#if defined(__cplusplus)
}
#endif

#endif  /* __MYDEMOCLIENT1_AM_USER_CONTEXT_H__ */
