/*******************************************************/
/* Generated by : PARSEC 5.1.1                         */
/*                Copyright Dassault Aviation          */
/*                date: 2021-11-15 14:06:44.590004     */
/*******************************************************/

#if !defined(_MYJUNIOR_OTHER_IMPL_USER_CONTEXT_HPP)
#define _MYJUNIOR_OTHER_IMPL_USER_CONTEXT_HPP

/*Standaard types*/
#include <ECOA.hpp>

/*Additionnaly created types*/
#include "ECOA.hpp"
#include "libmarx.hpp"
#include <pthread.h>

/*Container types*/
#include "myJunior_Other_impl_container_types.hpp"

namespace myJunior_Other_impl
{

	typedef struct
	{

          pthread_t thread_handle;
	} user_context;

	//Warm start Module Context structure example
	typedef struct
	{
		/* declare the Warm Start Module Context data here */

	} warm_start_context;

} /* myJunior_Other_impl */

#endif /* MYJUNIOR_OTHER_IMPL_USER_CONTEXT_HPP */
