/* Generated by PARSEC */
/* Module User Context Header for module myDemoPong3_AM */
#if !defined(_MYDEMOPONG3_AM_USER_CONTEXT_H)
#define _MYDEMOPONG3_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPong3_AM_user_context.h
 */

#include "mylib.h"


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myDemoPong3_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYDEMOPONG3_AM_USER_CONTEXT_H */
