/* Generated by PARSEC */
/* Module User Context Header for module myDemoPong_AM */
#if !defined(_MYDEMOPONG_AM_USER_CONTEXT_H)
#define _MYDEMOPONG_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPong_AM_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/

    /*********** START USER-WRITTEN USER ***********/
} myDemoPong_AM_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myDemoPong_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYDEMOPONG_AM_USER_CONTEXT_H */
