/* Generated by PARSEC */
/* Module User Context Header for module myDemoMaster_AM */
#if !defined(__MYDEMOMASTER_AM_USER_CONTEXT_H__)
#define __MYDEMOMASTER_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoMaster_AM_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/
	int timeout_received;
  /*********** USER ***********/
} myDemoMaster_AM_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myDemoMaster_AM_warm_start_context;

#if defined(__cplusplus)
}
#endif

#endif  /* __MYDEMOMASTER_AM_USER_CONTEXT_H__ */
