/* Generated by PARSEC */
/* Module User Context Header for module myDemoPong_AM */
#if !defined(_MYDEMOPONG_AM_USER_CONTEXT_H)
#define _MYDEMOPONG_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPong_AM_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
    ECOA__uint32 current_nb;
    ECOA__uint32 activating_error_num;
    char test_name[12];
  /*********** START USER-WRITTEN USER ***********/
} myDemoPong_AM_user_context;

#if defined(__cplusplus)
}
#endif

#endif  /* _MYDEMOPONG_AM_USER_CONTEXT_H */
