/* Generated by PARSEC */
/* Module Implementation myDemoMaster_AM */

#include "ECOA.h"
#include "myDemoMaster_AM.h"

#include "pingpong.h"
#include <assert.h>
#include "ldp_mod_container_util.h"


#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <apr_time.h>


int myDemoMaster_AM_log_trace(myDemoMaster_AM__context* context, const char *msg, ...) {
  ECOA__log log;
  va_list argp;
  va_start(argp, msg);
  vsnprintf((char *)&log.data, ECOA__LOG_MAXSIZE, msg, argp);
  va_end(argp);
  log.current_size = strnlen((char *)&log.data, ECOA__LOG_MAXSIZE);
  myDemoMaster_AM_container__log_trace(context, log);
  return log.current_size;
}

/* Entry points for lifecycle operations */
void myDemoMaster_AM__INITIALIZE__received(myDemoMaster_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoMaster_AM__REINITIALIZE__received(myDemoMaster_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoMaster_AM__START__received(myDemoMaster_AM__context* context)
{
  /* @TODO TODO - To be implemented */
    ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
  apr_sleep(200000);

	ECOA__uint32 ID_ext=0;
	ECOA__return_status ret = myDemoMaster_AM_container__req_Async_ext__request_async(context, &ID_ext);
  assert( ret == ECOA__return_status_OK);
  ret = myDemoMaster_AM_container__req_Async_ext2__request_async(context, &ID_ext);
  assert( ret == ECOA__return_status_OK);
	ECOA__uint32 ID_int=0;
	ret = myDemoMaster_AM_container__req_Async_int__request_async(context, &ID_int);
  assert( ret == ECOA__return_status_OK);


	ret = myDemoMaster_AM_container__req_Sync_ext__request_sync(context);
  assert( ret == ECOA__return_status_NO_RESPONSE);
  ret = myDemoMaster_AM_container__req_Sync_ext2__request_sync(context);
  assert( ret == ECOA__return_status_NO_RESPONSE);
	ret = myDemoMaster_AM_container__req_Sync_int__request_sync(context);
  assert( ret == ECOA__return_status_NO_RESPONSE);

  context->user.timeout_received = 0;
}

void myDemoMaster_AM__STOP__received(myDemoMaster_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoMaster_AM__SHUTDOWN__received(myDemoMaster_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}


void myDemoMaster_AM__req_Async_ext__response_received(myDemoMaster_AM__context* context, const ECOA__uint32 ID, const ECOA__return_status status)
{
  if(status != ECOA__return_status_NO_RESPONSE){
    myDemoMaster_AM_log_trace(context, "Received external asynchrone response : SHOULD be erased because of timeout !");
    myDemoMaster_AM_log_trace(context, "FAILED");
    assert(0);
  }else{
    context->user.timeout_received ++;
  }
}

void myDemoMaster_AM__req_Async_ext2__response_received(myDemoMaster_AM__context* context, const ECOA__uint32 ID, const ECOA__return_status status)
{
  if(status != ECOA__return_status_NO_RESPONSE){
    myDemoMaster_AM_log_trace(context, "Received external asynchrone response 2: SHOULD be erased because of timeout !");
    myDemoMaster_AM_log_trace(context, "FAILED");
    assert(0);
  }else{
    context->user.timeout_received ++;
  }
}


void myDemoMaster_AM__req_Async_int__response_received(myDemoMaster_AM__context* context, const ECOA__uint32 ID, const ECOA__return_status status)
{
  if(status != ECOA__return_status_NO_RESPONSE){
    myDemoMaster_AM_log_trace(context, "Received internal asynchrone response : SHOULD be erased because of timeout !");
    myDemoMaster_AM_log_trace(context, "FAILED");
    assert(0);
  }else{
    context->user.timeout_received ++;
  }
}

int finish_received=0;
void myDemoMaster_AM__finish__received(myDemoMaster_AM__context* context)
{
    ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
  myDemoMaster_AM_log_trace(context, "Finish received %i", finish_received++);
  myDemoMaster_AM_log_trace(context, "request sent in memory %i", ctx->req_resp.req_sent_list.current_size);

  //usleep(rand()%1000*1000);
  ECOA__uint32 ID_ext=0;

  if (finish_received == 6){
    if(ctx->req_resp.req_sent_list.current_size != 0){
      myDemoMaster_AM_log_trace(context, "A sent RR is always in memory. It is not clean properly");
      myDemoMaster_AM_log_trace(context, "FAILED");
      assert(0);
    }
    myDemoMaster_AM_log_trace(context, "timeout received : %i", context->user.timeout_received);
    assert(context->user.timeout_received == 3);
    myDemoMaster_AM_log_trace(context, "SUCCESS");
    ldp_kill_platform((ldp_module_context*)context->platform_hook);
  }
}