/* Generated by PARSEC */
/* Module Implementation myCompReader_mod_Writter */

#include "ECOA.h"
#include "myCompReader_mod_Writter.h"

#include "ECOA.h"
#include "VD_lib.h"
#include "assert.h"

/* Entry points for lifecycle operations */
void myCompReader_mod_Writter__INITIALIZE__received(myCompReader_mod_Writter__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod_Writter__START__received(myCompReader_mod_Writter__context* context)
{
	context->user.write_num = 0;
	myCompReader_mod_Writter_container__get_module_identifier_value(context, &context->user.mod_ID);

}

void myCompReader_mod_Writter__STOP__received(myCompReader_mod_Writter__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod_Writter__SHUTDOWN__received(myCompReader_mod_Writter__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod_Writter__trigger__received(myCompReader_mod_Writter__context* context)
{
	myCompReader_mod_Writter_container__write_vector_handle data_handle;
	ECOA__return_status ret;

	ret = myCompReader_mod_Writter_container__write_vector__get_write_access(context, &data_handle);
	if (ret == ECOA__return_status_DATA_NOT_INITIALIZED){
		assert(myCompReader_mod_Writter_container__write_vector__cancel_write_access(context, &data_handle) == ECOA__return_status_OK);
	}else{

		assert(data_handle.data->writter_0 == 1);

		ECOA__uint32* value_to_write;
		if (context->user.mod_ID == 1){
			value_to_write = &data_handle.data->writter_1;
		}else if (context->user.mod_ID == 2){
			value_to_write = &data_handle.data->writter_2;
		}else{
			value_to_write = &data_handle.data->writter_3;
		}
		assert(*value_to_write <= context->user.write_num);

		context->user.write_num++;
		*value_to_write = context->user.write_num;

		if (*value_to_write == 10){
			// every writter have written something
			myCompReader_mod_Writter_container__finish__send(context);

			printf("{[%i] (%i %i %i %i)\n",context->user.mod_ID
								  ,data_handle.data->writter_0
								  ,data_handle.data->writter_1
								  ,data_handle.data->writter_2
								  ,data_handle.data->writter_3);
			assert(myCompReader_mod_Writter_container__write_vector__cancel_write_access(context, &data_handle) == ECOA__return_status_OK);
		}else{
			assert(myCompReader_mod_Writter_container__write_vector__publish_write_access(context, &data_handle) == ECOA__return_status_OK);
		}
	}

}

