/* Generated by PARSEC */
/* Module Implementation Sender_AM */

#include "ECOA.h"
#include "Sender_AM.h"

#include "pingpong.h"
#include <stdio.h>
#include <stdarg.h>

static void print_log(Sender_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  Sender_AM_container__log_trace(context, log);
}

/* The following functions must be implemented by this module: */

/* Entrypoints for lifecycle events */
void Sender_AM__INITIALIZE__received(Sender_AM__context* context)
{
   /* One-shot initialisation activities: */
   /* @TODO TODO - To be implemented */

   /* Call REINITIALIZE entry-point: */
}

void Sender_AM__REINITIALIZE__received(Sender_AM__context* context)
{
}

void Sender_AM__START__received(Sender_AM__context* context)
{
}

void Sender_AM__STOP__received(Sender_AM__context* context)
{
   /* @TODO TODO - To be implemented */
}

void Sender_AM__SHUTDOWN__received(Sender_AM__context* context)
{
   /* @TODO TODO - To be implemented */
}

/* Entrypoints for module operations */
void 
Sender_AM__Run__received (
  Sender_AM__context* context
 )
{
   /* @TODO TODO - To be implemented */
	print_log(context, "Run");
	Sender_AM_container__Ping__send(context,12);
}
