/* Generated by PARSEC */
/* Module Implementation myDemoPong_AM */

#include "ECOA.h"
#include "myDemoPong_AM.h"

#include "pingpong.h"
#include <signal.h>

/* Entry points for lifecycle operations */
void myDemoPong_AM__INITIALIZE__received(myDemoPong_AM__context* context)
{
  context->user.nb=0;
}

void myDemoPong_AM__START__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__STOP__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__SHUTDOWN__received(myDemoPong_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_AM__Ping__received(myDemoPong_AM__context* context, const ECOA__uint16 nb_16, const ECOA__uint32 nb_msg)
{
  ECOA__uint32 ID;
  if (context->user.nb < 4)
  {
    ECOA__return_status return_status = myDemoPong_AM_container__Finish_counter__request_sync(context, context->user.nb);

    if (ECOA__return_status_OK == return_status)
    {
      context->user.nb++;

      if (context->user.nb == 3) {
        static int response_received=0;
        response_received++;

        myDemoPong_AM_container__Pong__send(context);

        if (response_received==2) // the two modules instance received response so kill the PD
        {
          kill(getpid(), SIGTERM);
        }
      }
    }
  }
}
