/* Generated by PARSEC */
/* Tests of the Module Implementation myElder_Main_impl */

#include "ECOA.h"
#include "myElder_Main_impl.h"

#include "ECOA.h"
#include "libmarx.h"

int main(int argc, char *argv[])
{
	myElder_Main_impl__context context;
	ECOA__uint32 ID;
	myElder_Main_impl__INITIALIZE__received(&context);
	myElder_Main_impl__START__received(&context);
	myElder_Main_impl__STOP__received(&context);
	myElder_Main_impl__SHUTDOWN__received(&context);

	myElder_Main_impl__activate__received(&context);

	libmarx__T_Data param;
	myElder_Main_impl__notification__received(&context, param);

    return 0;
}
