/* Generated by PARSEC */
/* Helpers for the Module Implementation myElder_Main_impl */

#include "ECOA.h"
#include "myElder_Main_impl.h"
#include "myElder_Main_impl_helpers.h"

#include "ECOA.h"
#include "libmarx.h"

int main(int argc, char *argv[])
{
	myElder_Main_impl__context context;

libmarx__T_Data libmarx__T_Data_data;
myElder_Main_impl__get_information(&context, &libmarx__T_Data_data);

    return 0;
}
