/* Generated by PARSEC */
/* Module Implementation myDemoPing_AM */

#include "ECOA.h"
#include "myDemoPing_AM.h"
#include <signal.h>
#include <stdio.h>
#include <unistd.h>
#include "pingpong.h"
#include <stdarg.h>
#include <assert.h>
#include "myDemoPing_External_Interface.h"
#include "apr_time.h"
#include "ldp_mod_container_util.h"

static void print_log(myDemoPing_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myDemoPing_AM_container__log_trace(context, log);
}

/* Entry points for lifecycle operations */
void myDemoPing_AM__INITIALIZE__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__REINITIALIZE__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__START__received(myDemoPing_AM__context* context)
{
  apr_sleep(200000);
  myDemoPing__Start_extern(60223, 31415);

  ECOA__duration delayDuration;
  delayDuration.seconds = 1;
  delayDuration.nanoseconds = 0;
  myDemoPing__Set_trigger_extern(&delayDuration, 60223, 31415);
  myDemoPing__Set_trigger_extern(&delayDuration, 60223, 31415);
}

void myDemoPing_AM__STOP__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__SHUTDOWN__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

int count =0;
void myDemoPing_AM__Pong__received(myDemoPing_AM__context* context)
{

  print_log(context, "Pong received !!");
  count++;

  if(count >= 3){

  print_log(context, "\033[1;32m SUCCESS  \033[0m");
  fflush(stdout);
  ldp_kill_platform((ldp_module_context*)context->platform_hook);
  }

}

void myDemoPing_AM__Start_test__received(myDemoPing_AM__context* context, const ECOA__uint32 param1, const ECOA__uint16 param2)
{
  print_log(context, "Send Ping");
  assert(param1 == 60223);
  assert(param2 == 31415);
  myDemoPing_AM_container__Ping__send(context);
}

