/* Generated by PARSEC */
/* Module Implementation myDummy_mod_impl */

#include "ECOA.h"
#include "myDummy_mod_impl.h"

#include "ECOA.h"
#include "lib_module.h"
#include <assert.h>
/* Entry points for lifecycle operations */
void myDummy_mod_impl__INITIALIZE__received(myDummy_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDummy_mod_impl__START__received(myDummy_mod_impl__context* context)
{
	myDummy_mod_impl_container__operation1__send(context);

	assert(myDummy_mod_impl_container__request1__request_sync(context) == ECOA__return_status_NO_RESPONSE);
	ECOA__uint32 ID;
	assert(myDummy_mod_impl_container__request2__request_async(context, &ID)== ECOA__return_status_NO_RESPONSE);

	// try to read data
	myDummy_mod_impl_container__read_data_handle data_handle;
	assert(myDummy_mod_impl_container__read_data__get_read_access(context, &data_handle) == ECOA__return_status_NO_DATA);
	assert(data_handle.data == 0);
	assert(data_handle.stamp == 0);

	assert(myDummy_mod_impl_container__read_data__release_read_access(context, &data_handle) == ECOA__return_status_INVALID_HANDLE);

	// try to write data
	myDummy_mod_impl_container__write_data_handle data_handle_w;

	assert(myDummy_mod_impl_container__write_data__get_write_access(context, &data_handle_w) == ECOA__return_status_DATA_NOT_INITIALIZED);
	assert(myDummy_mod_impl_container__write_data__cancel_write_access(context, &data_handle_w) == ECOA__return_status_OK);

	assert(myDummy_mod_impl_container__write_data__get_write_access(context, &data_handle_w) == ECOA__return_status_DATA_NOT_INITIALIZED);
	assert(data_handle_w.data != 0);
	assert(myDummy_mod_impl_container__write_data__publish_write_access(context, &data_handle_w) == ECOA__return_status_OK);

	assert(myDummy_mod_impl_container__write_data__get_write_access(context, &data_handle_w) == ECOA__return_status_OK);

}

void myDummy_mod_impl__STOP__received(myDummy_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDummy_mod_impl__SHUTDOWN__received(myDummy_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDummy_mod_impl__operation2__received(myDummy_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
	assert(0);
}

void myDummy_mod_impl__request2__response_received(myDummy_mod_impl__context* context, const ECOA__uint32 ID, const ECOA__return_status status)
{
  /* @TODO TODO - To be implemented */
	assert(0);
}

void myDummy_mod_impl__request3__request_received(myDummy_mod_impl__context* context, const ECOA__uint32 ID)
{
  /* @TODO TODO - To be implemented */
	assert(0);
}

