/* Generated by PARSEC */
/* Module Implementation myDemoFinish_AM */

#include "ECOA.h"
#include "myDemoFinish_AM.h"

#include "pingpong.h"
#include <signal.h>

/* Entry points for lifecycle operations */
void myDemoFinish_AM__INITIALIZE__received(myDemoFinish_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_AM__START__received(myDemoFinish_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_AM__STOP__received(myDemoFinish_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_AM__SHUTDOWN__received(myDemoFinish_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_AM__Finish_RR2__request_received(myDemoFinish_AM__context* context, const ECOA__uint32 ID, const ECOA__uint32 counter)
{
  static int finished_count=0;

  myDemoFinish_AM_container__Finish_RR2__response_send(context,ID);

  if (counter == 2)
  {
    finished_count++;

    if (finished_count==2) // finished for the 2 Pong instance then kill DemoFinish
    {
      pingpong__vector_data new_vector={150,150};
      myDemoFinish_AM_container__write_vector_handle handle;
      ECOA__return_status ret = myDemoFinish_AM_container__write_vector__get_write_access(context, &handle);

      memcpy(handle.data, &new_vector, sizeof(pingpong__vector_data) );

      ret=myDemoFinish_AM_container__write_vector__publish_write_access(context, &handle);

      kill(getpid(), SIGTERM);
    }
  }
}
