/**
* Copyright (c) 2023 Dassault Aviation
*
* SPDX-License-Identifier: MIT
*
* Generated by : LDP 1.0.0    
*                date: 2022-04-01 10:48:02.047975    
*/


/* Module Implementation myCadet_Main_impl */

#include "ECOA.h"
#include "myCadet_Main_impl.h"

#include "ECOA.h"
#include "libmarx.h"

#include <string.h>
#include <stdio.h>
#include <stdarg.h>

#define MTRACE    0
#define MDEBUG    1
#define MINFO     2
#define MWARNING  3

void
myCadet_Main_impl__log (myCadet_Main_impl__context * context, int level, char *msg, ...)
{
  ECOA__log log;
  va_list argp;

  va_start (argp, msg);
  vsnprintf ((char *) &log.data, ECOA__LOG_MAXSIZE, msg, argp);
  va_end (argp);
  log.current_size = strnlen ((char *) &log.data, ECOA__LOG_MAXSIZE);
  switch (level)
    {
    case MTRACE:
      myCadet_Main_impl_container__log_trace (context, log);
      break;
    case MDEBUG:
      myCadet_Main_impl_container__log_debug (context, log);
      break;
    case MINFO:
      myCadet_Main_impl_container__log_info (context, log);
      break;
    case MWARNING:
      myCadet_Main_impl_container__log_warning (context, log);
      break;
    default:
      myCadet_Main_impl_container__log_trace (context, log);
    }
}


/*
 * Entry points for lifecycle operations 
 */
void
myCadet_Main_impl__INITIALIZE__received (myCadet_Main_impl__context * context)
{
  context->user.id = 0;
  context->user.counter = 0;
  context->user.olderTransactionID = 0;
  context->user.youngerTransactionID = 0;
}

void
myCadet_Main_impl__START__received (myCadet_Main_impl__context * context)
{
  /*
   * @TODO TODO - To be implemented 
   */
}

void
myCadet_Main_impl__STOP__received (myCadet_Main_impl__context * context)
{
  /*
   * @TODO TODO - To be implemented 
   */
}

void
myCadet_Main_impl__SHUTDOWN__received (myCadet_Main_impl__context * context)
{
  /*
   * @TODO TODO - To be implemented 
   */
}

void
myCadet_Main_impl__older_command__received (myCadet_Main_impl__context * context, const libmarx__T_Data * param)
{
  myCadet_Main_impl_container__younger_command__send (context, param);
}

void
myCadet_Main_impl__younger_notification__received (myCadet_Main_impl__context * context, const libmarx__T_Data * param)
{
  myCadet_Main_impl_container__older_notification__send (context, param);
}

void
myCadet_Main_impl__younger_test_report__received (myCadet_Main_impl__context * context, const libmarx__T_TR_Set * param)
{
  myCadet_Main_impl_container__older_test_report__send (context, param);
}

void
myCadet_Main_impl__older_transaction__request_received (myCadet_Main_impl__context * context, const ECOA__uint32 ID,
                                                        const libmarx__T_Data * input)
{
  ECOA__return_status status;

  if (context->user.olderTransactionID != 0)
    {
      myCadet_Main_impl__log (context, MWARNING, "Double transaction !");
    }

  context->user.olderTransactionID = ID;

  status = myCadet_Main_impl_container__younger_transaction__request_async (context, &context->user.youngerTransactionID, input);
  if (status != ECOA__return_status_OK)
    {
      myCadet_Main_impl__log (context, MWARNING, "Error when sending request to Younger (%d)", status);
    }

}

void
myCadet_Main_impl__younger_transaction__response_received (myCadet_Main_impl__context * context, const ECOA__uint32 ID,
                                                           const ECOA__return_status status, const libmarx__T_Data * output)
{
  ECOA__return_status return_status;

  if (status != ECOA__return_status_OK)
    {
      myCadet_Main_impl__log (context, MWARNING, "Error with received response from Younger (%d)", status);
    }

  if (context->user.youngerTransactionID != ID)
    {
      myCadet_Main_impl__log (context, MWARNING, "Unknown response from Younger (%d)", status);
    }

  return_status = myCadet_Main_impl_container__older_transaction__response_send (context, context->user.olderTransactionID, output);
  if (return_status != ECOA__return_status_OK)
    {
      myCadet_Main_impl__log (context, MWARNING, "Error when responding to Older (%d)", return_status);
    }

  context->user.olderTransactionID = 0;
  context->user.youngerTransactionID = 0;
}


void
myCadet_Main_impl__younger_information__updated (myCadet_Main_impl__context * context)
{
  /*
   * @TODO TODO - To be implemented 
   */
}
