/* Generated by PARSEC */
/* Module Implementation myDemoPing_AM */

#include "ECOA.h"

#include "pingpong.h"
#include <assert.h>
#include <string.h>
/*#include "ldp_structures.h"
#include "ldp_mod_container_util.h"*/
#include "myDemoPing_AM.h"

/* Entry points for lifecycle operations */
void myDemoPing_AM__INITIALIZE__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__START__received(myDemoPing_AM__context* context)
{
	ECOA__byte memory_address[128];
	ECOA__uint32 out_size;

	/// private_pinfo_2
	assert(myDemoPing_AM_container__seek_private_pinfo_2(context, 5, ECOA__seek_whence_type_SEEK_SET, &out_size) == ECOA__return_status_OK);
	assert(out_size == 5);
	myDemoPing_AM_container__read_private_pinfo_2(context, memory_address, 5, &out_size);
	assert(out_size == 5);
	assert(strncmp((char*)memory_address,"common",out_size) == 0);

	/// private_pinfo_1
	assert(myDemoPing_AM_container__seek_private_pinfo_1(context, 5, ECOA__seek_whence_type_SEEK_SET, &out_size) == ECOA__return_status_OK);
	assert(out_size == 5);
	myDemoPing_AM_container__read_private_pinfo_1(context, memory_address, 6, &out_size);
	assert(out_size == 6);
	/*ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
	if(strcmp(ctx->name, "myDemoPing_1") == 0){
		assert(strncmp((char*)memory_address,"ping 1",out_size)==0);
	}else{
		assert(strncmp((char*)memory_address,"ping 2",out_size)==0);
	}*/

	/// public_pinfo_2
	assert(myDemoPing_AM_container__seek_public_pinfo_2(context, 5, ECOA__seek_whence_type_SEEK_SET, &out_size) == ECOA__return_status_OK);
	assert(out_size == 5);
	myDemoPing_AM_container__read_public_pinfo_2(context, memory_address, 21, &out_size);
	assert(out_size == 21);
	assert(strncmp((char*)memory_address,"assembly_pinfo_common",out_size) == 0);

	/// public_pinfo_1
	assert(myDemoPing_AM_container__seek_public_pinfo_1(context, 5, ECOA__seek_whence_type_SEEK_SET, &out_size) == ECOA__return_status_OK);
	assert(out_size == 5);
	myDemoPing_AM_container__read_public_pinfo_1(context, memory_address, 21, &out_size);
	/*if(strcmp(ctx->name, "myDemoPing_1") == 0){
		assert(strncmp((char*)memory_address,"assembly_pinfo_1",out_size)==0);
	}else{
		assert(strncmp((char*)memory_address,"component_pinfo_2",out_size)==0);
	}*/

	ECOA__log log;
	snprintf(log.data, ECOA__LOG_MAXSIZE,  "checked Pinfos : SUCCESS");
	myDemoPing_AM_container__log_trace(context, log);
}

void myDemoPing_AM__STOP__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__SHUTDOWN__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__TriggerPingEvent__received(myDemoPing_AM__context* context)
{
myDemoPing_AM_container__Ping__send(context);
}

void myDemoPing_AM__Pong__received(myDemoPing_AM__context* context)
{
	ECOA__log log;
	snprintf(log.data, ECOA__LOG_MAXSIZE,  "\033[1;32m SUCCESS  \033[0m");
	myDemoPing_AM_container__log_trace(context, log);

	/*ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;
	ldp_kill_platform(ctx);*/
}

