/* Generated by PARSEC */
/* Helpers for the Module Implementation myCadet_Main_impl */

#if !defined(MYCADET_MAIN_IMPL_HELPERS)
#define MYCADET_MAIN_IMPL_HELPERS
#include "ECOA.h"
#include "myCadet_Main_impl.h"

#include "ECOA.h"
#include "libmarx.h"

#if defined(__cplusplus)
extern "C" {
#endif

extern const char* MYCADET_MAIN_IMPL;

void myCadet_Main_impl_log_info(myCadet_Main_impl__context* context, char *msg, ...);
void myCadet_Main_impl_log(myCadet_Main_impl__context* context, char *msg, ...);


void myCadet_Main_impl__async_request_younger_transaction(myCadet_Main_impl__context* context, const ECOA__uint32 ID, libmarx__T_Data* input);

void myCadet_Main_impl__set_older_information(myCadet_Main_impl__context* context, libmarx__T_Data* data);
void myCadet_Main_impl__get_younger_information(myCadet_Main_impl__context* context, libmarx__T_Data* data);

#if defined(__cplusplus)
}
#endif
#endif /* MYCADET_MAIN_IMPL_HELPERS */
