/* Generated by PARSEC */
/* Helpers for the Module Implementation myCadet_Main_impl */

#include "ECOA.h"
#include "myCadet_Main_impl.h"
#include "myCadet_Main_impl_helpers.h"

#include "ECOA.h"
#include "libmarx.h"

int main(int argc, char *argv[])
{
	myCadet_Main_impl__context context;

libmarx__T_Data libmarx__T_Data_data;
myCadet_Main_impl__set_older_information(&context, &libmarx__T_Data_data);

    return 0;
}
