/* Generated by PARSEC */
/* Tests of the Module Implementation myCadet_Main_impl */

#include "ECOA.h"
#include "myCadet_Main_impl.h"

#include "ECOA.h"
#include "libmarx.h"

int main(int argc, char *argv[])
{
	myCadet_Main_impl__context context;
	ECOA__uint32 ID;
	myCadet_Main_impl__INITIALIZE__received(&context);
	myCadet_Main_impl__START__received(&context);
	myCadet_Main_impl__STOP__received(&context);
	myCadet_Main_impl__SHUTDOWN__received(&context);

	libmarx__T_Data param;
	myCadet_Main_impl__older_command__received(&context, param);

	myCadet_Main_impl__younger_notification__received(&context, param);

	libmarx__T_Data input;
	libmarx__T_Data output;
	myCadet_Main_impl__older_transaction__request_received(&context, ID, &input);

    return 0;
}
