/* Module Test Container Implementation Skeleton for myCadet_Main_impl */

/* @file myCadet_Main_impl_test_container.c
 * This is the Module Test Container for Module myCadet_Main_impl
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by PARSEC */

#include <stdlib.h>

#include "ECOA.h"
#include "myCadet_Main_impl_container.h"

#include "ECOA.h"
#include "libmarx.h"

void myCadet_Main_impl_container__older_notification__send(myCadet_Main_impl__context* context, const libmarx__T_Data* param)
{
  /* @TODO TODO - To be implemented */
}

void myCadet_Main_impl_container__younger_command__send(myCadet_Main_impl__context* context, const libmarx__T_Data* param)
{
  /* @TODO TODO - To be implemented */
}

ECOA__return_status myCadet_Main_impl_container__younger_transaction__request_async(myCadet_Main_impl__context* context, ECOA__uint32* ID, const libmarx__T_Data* input)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;  return return_status;}

ECOA__return_status myCadet_Main_impl_container__older_transaction__response_send(myCadet_Main_impl__context* context, const ECOA__uint32 ID, libmarx__T_Data* output)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;  return return_status;}

ECOA__return_status myCadet_Main_impl_container__older_information__get_write_access(myCadet_Main_impl__context* context, myCadet_Main_impl_container__older_information_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  data_handle->data = malloc(sizeof(libmarx__T_Data));
  return return_status;
}

ECOA__return_status myCadet_Main_impl_container__older_information__cancel_write_access(myCadet_Main_impl__context* context, myCadet_Main_impl_container__older_information_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

ECOA__return_status myCadet_Main_impl_container__older_information__publish_write_access(myCadet_Main_impl__context* context, myCadet_Main_impl_container__older_information_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  free(data_handle->data);
  return return_status;
}


ECOA__return_status myCadet_Main_impl_container__younger_information__get_read_access(myCadet_Main_impl__context* context, myCadet_Main_impl_container__younger_information_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_INVALID_HANDLE;
  return return_status;
}

ECOA__return_status myCadet_Main_impl_container__younger_information__release_read_access(myCadet_Main_impl__context* context, myCadet_Main_impl_container__younger_information_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_INVALID_HANDLE;
  return return_status;
}


/* Properties API */

/* Logging services API call specifications */
void myCadet_Main_impl_container__log_trace(myCadet_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myCadet_Main_impl_container__log_debug(myCadet_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myCadet_Main_impl_container__log_info(myCadet_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myCadet_Main_impl_container__log_warning(myCadet_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myCadet_Main_impl_container__raise_error(myCadet_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myCadet_Main_impl_container__raise_fatal_error(myCadet_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}


/* Recovery action service API call specification if the module is a Fault Handler */

/* Time Services API call specifications */
void myCadet_Main_impl_container__get_relative_local_time(myCadet_Main_impl__context* context, ECOA__hr_time *relative_local_time)
{
  /* @TODO TODO - To be implemented */
}

ECOA__return_status myCadet_Main_impl_container__get_UTC_time(myCadet_Main_impl__context* context, ECOA__global_time *utc_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

ECOA__return_status myCadet_Main_impl_container__get_absolute_system_time(myCadet_Main_impl__context* context, ECOA__global_time *absolute_system_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

void myCadet_Main_impl_container__get_relative_local_time_resolution(myCadet_Main_impl__context* context, ECOA__duration *relative_local_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myCadet_Main_impl_container__get_UTC_time_resolution(myCadet_Main_impl__context* context, ECOA__duration *utc_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myCadet_Main_impl_container__get_absolute_system_time_resolution(myCadet_Main_impl__context* context, ECOA__duration *absolute_system_time_resolution)
{
  /* @TODO TODO - To be implemented */
}


