/* Generated by PARSEC */
/* Module Implementation myCompReader_mod */

#include "ECOA.h"
#include "myCompReader_mod.h"

#include "VD_lib.h"
#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <stdarg.h>

static void print_log(myCompReader_mod__context* context, const char *format, ...){
	va_list vl;
	ECOA__log log;

	va_start(vl, format);
	vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
	va_end( vl);

	myCompReader_mod_container__log_trace(context, log);
}
/* Entry points for lifecycle operations */
void myCompReader_mod__INITIALIZE__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod__START__received(myCompReader_mod__context* context)
{
	context->user.saved_vector.nb_x = 0;
	context->user.saved_vector.nb_y = 0;
}

void myCompReader_mod__STOP__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod__SHUTDOWN__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod__read_vector__updated(myCompReader_mod__context* context){
myCompReader_mod_container__read_vector_handle data_handle;

	int ret = myCompReader_mod_container__read_vector__get_read_access(context, &data_handle);
	assert(ret== ECOA__return_status_OK);

	print_log(context, "(%i, %i) (%i %i)",context->user.saved_vector.nb_x, context->user.saved_vector.nb_y,
								data_handle.data->nb_x, data_handle.data->nb_y);

	assert(context->user.saved_vector.nb_x <= data_handle.data->nb_x || context->user.saved_vector.nb_y <= data_handle.data->nb_y);
	memcpy(&context->user.saved_vector, data_handle.data, sizeof(VD_lib__vector_data));

	ret = myCompReader_mod_container__read_vector__release_read_access(context, &data_handle);
	assert(ret == ECOA__return_status_OK);

	if(context->user.saved_vector.nb_x > 20 &&  context->user.saved_vector.nb_y > 20){
		myCompReader_mod_container__finish__send( context);
	}
}

