/* Generated by PARSEC */
/* Module Implementation myDemoServer_mod_impl */

#include "ECOA.h"
#include "myDemoServer_mod_impl.h"

#include "pingpong.h"

/* Entry points for lifecycle operations */
void myDemoServer_mod_impl__INITIALIZE__received(myDemoServer_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_mod_impl__START__received(myDemoServer_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_mod_impl__STOP__received(myDemoServer_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_mod_impl__SHUTDOWN__received(myDemoServer_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_mod_impl__RR_msg__request_received(myDemoServer_mod_impl__context* context, const ECOA__uint32 ID, const pingpong__T_2D_Position* Ping_Position, const ECOA__uint32 Ping_Target)
{
	ECOA__uint32 Pong_Target= Ping_Target +10;

printf("RR received local %i (comp : %i, mod : %i)\n", Ping_Target, Ping_Position->Latitude, Ping_Position->Longitude);
  myDemoServer_mod_impl_container__RR_msg__response_send(context, ID,  Ping_Position,  Pong_Target);

}

