/*******************************************************/
/*
 * Generated by : PARSEC 5.1.1 
 */
/*
 * Copyright Dassault Aviation 
 */
/*
 * date: 2021-10-28 17:32:58.485951 
 */
/*******************************************************/


/*
 * Module User Context Header for module myJunior_Main_impl 
 */
#if !defined(_MYJUNIOR_MAIN_IMPL_USER_CONTEXT_H)
#define _MYJUNIOR_MAIN_IMPL_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C"
{
#endif

  /*
   * @file myJunior_Main_impl_user_context.h
   */

#include "ECOA.h"
#include "libmarx.h"
#include <pthread.h>
  /*
   * Module User Context Structure 
   */
  typedef struct
  {
    /*********** START USER-WRITTEN USER ***********/
    libmarx__T_Data data_1;
    libmarx__T_Data data_2;
    pthread_t thread_handle;
    /*********** END USER-WRITTEN USER ***********/
  } myJunior_Main_impl_user_context;


  /*
   * Warm start Module Context structure 
   */
  typedef struct
  {
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
  } myJunior_Main_impl_warm_start_context;

#if defined(__cplusplus)
}
#endif
#endif                          /* _MYJUNIOR_MAIN_IMPL_USER_CONTEXT_H */
