/* Generated by PARSEC */
/* Module Implementation Logger_AM */

#include "ECOA.h"
#include "Logger_AM.h"

#include "pingpong.h"
#include "ldp_structures.h"
#include "apr_time.h"

/* Entry points for lifecycle operations */
void Logger_AM__INITIALIZE__received(Logger_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void Logger_AM__REINITIALIZE__received(Logger_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void Logger_AM__START__received(Logger_AM__context* context)
{
  /* @TODO TODO - To be implemented */
	ECOA__log log ={6,"Logger"};
	apr_sleep(200000);

	Logger_AM_container__log_trace(context, log);
	Logger_AM_container__log_debug(context, log);
	Logger_AM_container__log_info(context, log);
	Logger_AM_container__log_warning(context, log);
	Logger_AM_container__raise_error(context, log, 0);
	Logger_AM_container__raise_fatal_error(context, log, 0);

	Logger_AM_container__Finish__send(context);
}

void Logger_AM__STOP__received(Logger_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void Logger_AM__SHUTDOWN__received(Logger_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void Logger_AM__Finish__received(Logger_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

