/* Generated by PARSEC */
/* Module Implementation mydemoServer_AM */

#include "ECOA.h"
#include "../inc-gen/mydemoServer_AM.h"
#include <stdio.h>
#include "mylib.h"
#include "../inc/test_lib.h"

#include <stdarg.h>
//#include <apr_time.h>

static void print_log(mydemoServer_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  mydemoServer_AM_container__log_trace(context, log);
}
/* Entry points for lifecycle operations */
void mydemoServer_AM__INITIALIZE__received(mydemoServer_AM__context* context)
{
  //test_lib_do_job();
}

void mydemoServer_AM__REINITIALIZE__received(mydemoServer_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void mydemoServer_AM__START__received(mydemoServer_AM__context* context)
{
  /* @TODO TODO - To be implemented */
	print_log(context, "write ping ");
  //apr_sleep(200000);
	mydemoServer_AM_container__SPing1__send(context);
mydemoServer_AM_container__SPing0__send(context);


}

void mydemoServer_AM__STOP__received(mydemoServer_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void mydemoServer_AM__SHUTDOWN__received(mydemoServer_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}
