/* Generated by PARSEC */
/* Module User Context Header for module mydemoFinal_AM */
#if !defined(__MYDEMOFINAL_AM_USER_CONTEXT_H__)
#define __MYDEMOFINAL_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file mydemoFinal_AM_user_context.h
 */

/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/

  /*********** USER ***********/
} mydemoFinal_AM_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} mydemoFinal_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYDEMOFINAL_AM_USER_CONTEXT_H__ */
