/*******************************************************/
/* Generated by : PARSEC 5.1.1                         */
/*                Copyright Dassault Aviation          */
/*                date: 2021-10-28 17:32:58.482162     */
/*******************************************************/


/*
 * Module User Context Header for module myCadet_Main_impl 
 */
#if !defined(_MYCADET_MAIN_IMPL_USER_CONTEXT_H)
#define _MYCADET_MAIN_IMPL_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C"
{
#endif

  /*
   * @file myCadet_Main_impl_user_context.h
   */

#include "ECOA.h"
#include "libmarx.h"
  /*
   * Module User Context Structure 
   */
  typedef struct
  {
    /*********** START USER-WRITTEN USER ***********/
    ECOA__uint32 id;
    libmarx__T_PositiveInteger counter;
    ECOA__uint32 olderTransactionID;
    ECOA__uint32 youngerTransactionID;
    /*********** END USER-WRITTEN USER ***********/
  } myCadet_Main_impl_user_context;


  /*
   * Warm start Module Context structure 
   */
  typedef struct
  {
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
  } myCadet_Main_impl_warm_start_context;

#if defined(__cplusplus)
}
#endif
#endif                          /* _MYCADET_MAIN_IMPL_USER_CONTEXT_H */
