/* Generated by PARSEC */
/* Module Implementation myDemoPing_mod */

#include "ECOA.h"
#include "myDemoPing_mod.h"

#include "lib_array.h"

#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include "ldp_mod_container_util.h"

static void print_log(myDemoPing_mod__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myDemoPing_mod_container__log_trace(context, log);
}

static void fill_array(myDemoPing_mod__context* context, ECOA__uint32* array, int size){
  for ( int i=0; i<size; i++){
    array[i] = context->user.nb_pong + i;
  }
  array[0] = 0XA0CE + context->user.nb_pong;
  array[size -1] = 0XA0CE;
}

/* Entry points for lifecycle operations */
void myDemoPing_mod__INITIALIZE__received(myDemoPing_mod__context* context)
{
  /* @TODO TODO - To be implemented */
  context->user.nb_pong = 0;
}

void myDemoPing_mod__REINITIALIZE__received(myDemoPing_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_mod__START__received(myDemoPing_mod__context* context)
{
  /* @TODO TODO - To be implemented */
  lib_array__array_1k* array_1k = calloc(1, sizeof(lib_array__array_1k));
  lib_array__array_4k* array_4k = calloc(1, sizeof(lib_array__array_4k));
  lib_array__array_16k* array_16k = calloc(1, sizeof(lib_array__array_16k));
  lib_array__array_64k* array_64k = calloc(1, sizeof(lib_array__array_64k));
  lib_array__array_256k* array_256k = calloc(1, sizeof(lib_array__array_256k));
  lib_array__array_10m* array_10m = calloc(1, sizeof(lib_array__array_10m));

  fill_array(context, *array_1k,lib_array__array_1k_MAXSIZE );
  myDemoPing_mod_container__Ping_array_1k__send(context, array_1k);
  context->user.nb_pong++;
  fill_array(context, *array_4k,lib_array__array_4k_MAXSIZE );
  myDemoPing_mod_container__Ping_array_4k__send(context, array_4k);
  context->user.nb_pong++;
  fill_array(context, *array_16k,lib_array__array_16k_MAXSIZE );
  myDemoPing_mod_container__Ping_array_16k__send(context, array_16k);
  context->user.nb_pong++;
  fill_array(context, *array_64k,lib_array__array_64k_MAXSIZE );
  myDemoPing_mod_container__Ping_array_64k__send(context, array_64k);
  context->user.nb_pong++;
  fill_array(context, *array_256k,lib_array__array_256k_MAXSIZE );
  myDemoPing_mod_container__Ping_array_256k__send(context, array_256k);
  context->user.nb_pong++;
  fill_array(context, *array_10m, lib_array__array_10m_MAXSIZE );
  myDemoPing_mod_container__Ping_array_10m__send(context, array_10m);

  free(array_1k);
  free(array_4k);
  free(array_16k);
  free(array_64k);
  free(array_256k);
  free(array_10m);
}

void myDemoPing_mod__STOP__received(myDemoPing_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_mod__SHUTDOWN__received(myDemoPing_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_mod__Pong__received(myDemoPing_mod__context* context)
{
  context->user.nb_pong++;
  print_log(context, "Pong received : %i \n", context->user.nb_pong);

  if (context->user.nb_pong++ == 1000){
    print_log(context, "\033[1;32m SUCCESS  \033[0m");
    fflush(stdout);
    ldp_kill_platform((ldp_module_context*)context->platform_hook);
  }

  switch (context->user.nb_pong % 6){
    case 0 :
    {
      lib_array__array_1k* array_1k = calloc(1, sizeof(lib_array__array_1k));
      fill_array(context, *array_1k,lib_array__array_1k_MAXSIZE );
      myDemoPing_mod_container__Ping_array_1k__send(context, array_1k);
      free(array_1k);
      break;
    }
    case 1:
    {
      lib_array__array_4k* array_4k = calloc(1, sizeof(lib_array__array_4k));
      fill_array(context, *array_4k,lib_array__array_4k_MAXSIZE );
      myDemoPing_mod_container__Ping_array_4k__send(context, array_4k);
      free(array_4k);
      break;
    }
    case 2:
    {
      lib_array__array_16k* array_16k = calloc(1, sizeof(lib_array__array_16k));
      fill_array(context, *array_16k,lib_array__array_16k_MAXSIZE );
      myDemoPing_mod_container__Ping_array_16k__send(context, array_16k);
      free(array_16k);
      break;
    }
    case 3:
    {
      lib_array__array_64k* array_64k = calloc(1, sizeof(lib_array__array_64k));
      fill_array(context, *array_64k,lib_array__array_64k_MAXSIZE );
      myDemoPing_mod_container__Ping_array_64k__send(context, array_64k);
      free(array_64k);
      break;
    }
    case 4:
    {
      lib_array__array_256k* array_256k = calloc(1, sizeof(lib_array__array_256k));
      fill_array(context, *array_256k,lib_array__array_256k_MAXSIZE );
      myDemoPing_mod_container__Ping_array_256k__send(context, array_256k);
      free(array_256k);
      break;
    }
    case 5:
     {
      lib_array__array_10m* array_10m = calloc(1, sizeof(lib_array__array_10m));
      fill_array(context, *array_10m,lib_array__array_10m_MAXSIZE );
      myDemoPing_mod_container__Ping_array_10m__send(context, array_10m);
      free(array_10m);
      break;
    }

    default:
      print_log(context, "WHAT ??");
      break;
  }
}
