/* Generated by PARSEC */
/* Module Implementation myDummy_mod_impl2 */

#include "ECOA.h"
#include "myDummy_mod_impl2.h"

#include "ECOA.h"
#include "lib_module.h"
#include <assert.h>

/* Entry points for lifecycle operations */
void myDummy_mod_impl2__INITIALIZE__received(myDummy_mod_impl2__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDummy_mod_impl2__START__received(myDummy_mod_impl2__context* context)
{
	myDummy_mod_impl2_container__operation1__send(context);

	assert(myDummy_mod_impl2_container__request1__request_sync(context) == ECOA__return_status_NO_RESPONSE);
	ECOA__uint32 ID;
	assert(myDummy_mod_impl2_container__request2__request_async(context, &ID)== ECOA__return_status_NO_RESPONSE);

	// try to read data
	myDummy_mod_impl2_container__read_data_handle data_handle;
	assert(myDummy_mod_impl2_container__read_data__get_read_access(context, &data_handle) == ECOA__return_status_NO_DATA);
	assert(data_handle.data == 0);
	assert(data_handle.stamp == 0);

	assert(myDummy_mod_impl2_container__read_data__release_read_access(context, &data_handle) == ECOA__return_status_INVALID_HANDLE);

	// try to write data
	myDummy_mod_impl2_container__write_data_handle data_handle_w;

	assert(myDummy_mod_impl2_container__write_data__get_write_access(context, &data_handle_w) == ECOA__return_status_DATA_NOT_INITIALIZED);
	assert(myDummy_mod_impl2_container__write_data__cancel_write_access(context, &data_handle_w) == ECOA__return_status_OK);

	assert(myDummy_mod_impl2_container__write_data__get_write_access(context, &data_handle_w) == ECOA__return_status_DATA_NOT_INITIALIZED);
	assert(data_handle_w.data != 0);
	assert(myDummy_mod_impl2_container__write_data__publish_write_access(context, &data_handle_w) == ECOA__return_status_OK);

	assert(myDummy_mod_impl2_container__write_data__get_write_access(context, &data_handle_w) == ECOA__return_status_OK);
}

void myDummy_mod_impl2__STOP__received(myDummy_mod_impl2__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDummy_mod_impl2__SHUTDOWN__received(myDummy_mod_impl2__context* context)
{
  /* @TODO TODO - To be implemented */
}

