/* Generated by PARSEC */
/* Module Implementation myDemoPing_AM */
#define _GNU_SOURCE
#include <unistd.h>
// OD BEGIN
#if !defined(PIKEOS_POSIX)
#include <sys/syscall.h>
#endif
// OD END
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <sched.h>
#include <stdarg.h>

#include "ECOA.h"
#include "myDemoPing_AM.h"

#include "pingpong.h"
#include <assert.h>
#include "ldp_fifo_manager.h"
#include "ldp_structures.h"

static void print_log(myDemoPing_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

    myDemoPing_AM_container__log_trace(context, log);
}

static void print_deployment_info(myDemoPing_AM__context* context, cpu_set_t cpumask, int priority, int niceness, int sched_policy){
  char string[256];

  char cpu_mask_str[4*CPU_SETSIZE];
  for(int i=0; i<4;i++){
    if(CPU_ISSET(i, &cpumask)){
      snprintf(&cpu_mask_str[i*2],4,"|%d",i);
    }else{
      sprintf(&cpu_mask_str[i*2],"| ");
    }
  }
  snprintf(string, 256, " sched_policy:%i\n priority:%i\n niceness:%i\n cpu mask: %s\n",
                      sched_policy,
                      priority,
                      niceness,
                      cpu_mask_str);
  print_log(context, "%s", string);
}


/* Entry points for lifecycle operations */
void myDemoPing_AM__INITIALIZE__received(myDemoPing_AM__context* context)
{
  ECOA__uint32 comp_ID;
  char test_name[12];
  myDemoPing_AM_container__get_comp_ID_value(context, &comp_ID);
  if (comp_ID == 10){
    strcpy(context->user.test_name, "internal PD");
  }else{
    strcpy(context->user.test_name, "external PD");
  }

	context->user.current_nb =0;
	context->user.data_r_value=0;
	context->user.pong_nb =0;
	context->user.tick_nb =0;
  context->user.activating_error_num = 0;
}

void myDemoPing_AM__START__received(myDemoPing_AM__context* context)
{
  pthread_t thread=pthread_self();
// OD BEGIN
#if !defined(PIKEOS_POSIX)
  int tid = syscall(SYS_gettid);
#endif
// OD END

  cpu_set_t cpuget;
  int sched_policy = -1;
  struct sched_param sched_param;
  int niceness = -1;

  pthread_getaffinity_np(thread,
// OD BEGIN
#if !defined(PIKEOS_POSIX)
                         sizeof(cpu_set_t),
#endif
// OD END
                         &cpuget);
  pthread_getschedparam(thread, &sched_policy, &sched_param);
// OD BEGIN
#if defined(PIKEOS_POSIX)
  niceness = 0; // default value of  getpriority(PRIO_PROCESS, 
#else
  niceness = getpriority(PRIO_PROCESS, tid);
#endif
// OD END
  print_deployment_info(context,cpuget, sched_param.sched_priority, niceness, sched_policy );

  /* assert(!CPU_ISSET(0, &cpuget)); */
  /* assert(!CPU_ISSET(1, &cpuget)); */
  /* assert(!CPU_ISSET(2, &cpuget)); */
  /* assert(CPU_ISSET(3, &cpuget)); */

  /* if(geteuid() == 0){ */
  /*   /\*root *\/ */
  /*   assert(sched_policy == SCHED_FIFO); */
  /*   assert(sched_param.sched_priority != 0); */
  /*   assert(niceness == 0); */
  /* } else { */
  /*   /\* Anything goes. *\/ */
  /*   assert(sched_policy == SCHED_OTHER); */
  /*   assert(sched_param.sched_priority == 0); */
  /*   assert(niceness == 0); */
  /* } */

  context->user.RR_answer_nb = 0;
}

void myDemoPing_AM__STOP__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__SHUTDOWN__received(myDemoPing_AM__context* context)
{
  // activating operation error
  if (context->user.activating_error_num > 0){
    print_log(context, "[myDemoPing][%s] \033[1;31m FAILED \033[0m, %i errors of non-activating operations",
              context->user.test_name,
              context->user.activating_error_num);
    // wait and raise error
    sleep(2);
    assert(0);
  }
}

bool first_tick=true;
void myDemoPing_AM__TriggerEvent__received(myDemoPing_AM__context* context)
{
  if (context->user.tick_nb % 2){
    // send new data
    print_log(context,"Tick %i : send data",context->user.tick_nb);
    if( ! first_tick){
      //check received all pong
      assert(context->user.pong_nb == 6);
      context->user.pong_nb = 0;

      // recieved update
      assert(context->user.data_r_value == context->user.tick_nb/2);

      //received RR response
      assert(context->user.RR_answer_nb == 1);
      context->user.RR_answer_nb = 0;

      context->user.current_nb++;

      //received dynamic trigger event
      assert(context->user.dyn_trig_value == context->user.tick_nb-2);

    }
    ECOA__uint32 ID;
    first_tick = false;
    myDemoPing_AM_container__Ping_ASync__request_async(context, &ID);
    myDemoPing_AM_container__Ping__send(context, context->user.current_nb);
    myDemoPing_AM_container__Ping__send(context, context->user.current_nb);
    myDemoPing_AM_container__Ping__send(context, context->user.current_nb);
    myDemoPing_AM_container__Ping__send(context, context->user.current_nb);
    myDemoPing_AM_container__Ping__send(context, context->user.current_nb);
    myDemoPing_AM_container__Ping__send(context, context->user.current_nb);
    ECOA__duration waiting_time={0, 3*1000*1000};
    myDemoPing_AM_container__dyn_trig_set__send(context,
                                                &waiting_time,
                                                context->user.tick_nb);
  }else{
    // read all in messages
    // nothing to do here
    print_log(context,"Tick %i : received data",context->user.tick_nb);
  }

  context->user.tick_nb++;
	// stop test
	if(context->user.tick_nb > 5){
		ldp_kill_platform((ldp_module_context*)context->platform_hook);
	}
}

void myDemoPing_AM__Pong__received(myDemoPing_AM__context* context, const ECOA__uint32 nb_msg)
{
	// Pong should arrived before triggerEvent
	assert(nb_msg == context->user.current_nb);
	context->user.pong_nb++;

	// But should be poped after triggerEvent arrived in FIFO
	// => check current number of activating operation if FIFO
  int current_activ_op = ((ldp_module_context*)context->platform_hook)->fifo_manager->activating_op_num;
	if(current_activ_op <= 0){
		print_log(context, "[myDemoPing][%s] ERROR : no activating operations in FIFO (event)",
              context->user.test_name);
    context->user.activating_error_num++;
	}else{
    print_log(context, "[myDemoPing][%s] activating operations in FIFO (Pong received) : %i",
              context->user.test_name,
              current_activ_op);
  }
}


void myDemoPing_AM__data_r__updated(myDemoPing_AM__context* context){
	myDemoPing_AM_container__data_r_handle data_handle;
	int ret=myDemoPing_AM_container__data_r__get_read_access(context, &data_handle);
	assert(ret== LDP_SUCCESS);
	memcpy(&context->user.data_r_value, data_handle.data, sizeof(ECOA__uint32) );
	ret=myDemoPing_AM_container__data_r__release_read_access(context, &data_handle);
	assert(ret == LDP_SUCCESS);
	// But should be poped after triggerEvent arrived in FIFO
	// => check current number of activating operation if FIFO
  int current_activ_op =  ((ldp_module_context*)context->platform_hook)->fifo_manager->activating_op_num;
	if(current_activ_op <= 0){
		print_log(context, "[myDemoPing][%s] ERROR : no activating operations in FIFO (VD notif)\n",
              context->user.test_name);
    context->user.activating_error_num++;
	}else{
    print_log(context, "[myDemoPing][%s] activating operations in FIFO (VD notif) : %i",
              context->user.test_name,
              current_activ_op);
  }
}


void myDemoPing_AM__Ping_ASync__response_received(myDemoPing_AM__context* context, const ECOA__uint32 ID, const ECOA__return_status status){
	assert(status == ECOA__return_status_OK);
  context->user.RR_answer_nb++;

  // But should be poped after triggerEvent arrived in FIFO
	// => check current number of activating operation if FIFO
  int current_activ_op =  ((ldp_module_context*)context->platform_hook)->fifo_manager->activating_op_num;
	if(current_activ_op <= 0){
		print_log(context, "[myDemoPing][%s] ERROR : no activating operations in FIFO (Async Response received)",
              context->user.test_name);
    context->user.activating_error_num++;
	}else{
    print_log(context, "[myDemoPing][%s] activating operations in FIFO (Asyn response received) : %i",
              context->user.test_name,
              current_activ_op);
  }
}

void myDemoPing_AM__dyn_trig_event__received(myDemoPing_AM__context* context,
                                             const ECOA__int32 parma1){
  context->user.dyn_trig_value = parma1;

  // But should be poped after triggerEvent arrived in FIFO
	// => check current number of activating operation if FIFO
  int current_activ_op =  ((ldp_module_context*)context->platform_hook)->fifo_manager->activating_op_num;
	if(current_activ_op <= 0){
		print_log(context, "[myDemoPing][%]] ERROR : no activating operations in FIFO (DynTrigger)",
              context->user.test_name);
    context->user.activating_error_num++;
	}else{
    print_log(context, "[myDemoPing][%s] activating operations in FIFO (DynTrigger) : %i",
              context->user.test_name,
              current_activ_op);
  }
}
