/* Generated by PARSEC */
/* Module User Context Header for module mydemoServer_AM */
#if !defined(__MYDEMOSERVER_AM_USER_CONTEXT_H__)
#define __MYDEMOSERVER_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file mydemoServer_AM_user_context.h
 */

/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/

  /*********** USER ***********/
} mydemoServer_AM_user_context;

typedef struct
{

} mydemoServer_AM_warm_start_context;
#if defined(__cplusplus)
}
#endif

#endif  /* __MYDEMOSERVER_AM_USER_CONTEXT_H__ */
