/* Generated by PARSEC */
/* Module User Context Header for module myCompFinisher_mod */
#if !defined(__MYCOMPFINISHER_MOD_USER_CONTEXT_H__)
#define __MYCOMPFINISHER_MOD_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myCompFinisher_mod_user_context.h
 */

/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/
	int nb_finish;
  /*********** USER ***********/
} myCompFinisher_mod_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myCompFinisher_mod_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYCOMPFINISHER_MOD_USER_CONTEXT_H__ */
