/* Generated by PARSEC */
/* Tests of the Module Implementation myJunior_Main_impl */

#include "ECOA.h"
#include "myJunior_Main_impl.h"

#include "ECOA.h"
#include "libmarx.h"

int main(int argc, char *argv[])
{
	myJunior_Main_impl__context context;
	ECOA__uint32 ID;
	myJunior_Main_impl__INITIALIZE__received(&context);
	myJunior_Main_impl__START__received(&context);
	myJunior_Main_impl__STOP__received(&context);
	myJunior_Main_impl__SHUTDOWN__received(&context);

	ECOA__uint32 param;
	myJunior_Main_impl__TheFeedback__received(&context, param);

	myJunior_Main_impl__command__received(&context, param);

	libmarx__T_Data input;
	libmarx__T_Data output;
	myJunior_Main_impl__transaction__request_received(&context, ID, &input);

    return 0;
}
