/* Generated by PARSEC */
/* Helpers for the Module Implementation myJunior_Main_impl */

#if !defined(MYJUNIOR_MAIN_IMPL_HELPERS)
#define MYJUNIOR_MAIN_IMPL_HELPERS
#include "ECOA.h"
#include "myJunior_Main_impl.h"

#include "ECOA.h"
#include "libmarx.h"

#if defined(__cplusplus)
extern "C" {
#endif

extern const char* MYJUNIOR_MAIN_IMPL;

void myJunior_Main_impl_log_info(myJunior_Main_impl__context* context, char *msg, ...);
void myJunior_Main_impl_log(myJunior_Main_impl__context* context, char *msg, ...);


void myJunior_Main_impl__set_information(myJunior_Main_impl__context* context, libmarx__T_Data* data);

#if defined(__cplusplus)
}
#endif
#endif /* MYJUNIOR_MAIN_IMPL_HELPERS */
