/* Generated by PARSEC */
/* Helpers for the Module Implementation myJunior_Main_impl */

#include "ECOA.h"
#include "myJunior_Main_impl.h"
#include "myJunior_Main_impl_helpers.h"

#include "ECOA.h"
#include "libmarx.h"

int main(int argc, char *argv[])
{
	myJunior_Main_impl__context context;

libmarx__T_Data libmarx__T_Data_data;
myJunior_Main_impl__set_information(&context, &libmarx__T_Data_data);

    return 0;
}
