/* Module Helpers Implementation for myJunior_Main_impl */

/* @file myJunior_Main_impl_helpers.c
 * This is the Module Test Container for Module myJunior_Main_impl
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by PARSEC */

#include <stdio.h>
#include <string.h>
#include <stdarg.h>

#include "ECOA.h"
#include "myJunior_Main_impl_container.h"
#include "myJunior_Main_impl_helpers.h"

#include "ECOA.h"
#include "libmarx.h"


const char* MYJUNIOR_MAIN_IMPL = "MYJUNIOR_MAIN_IMPL: ";

void myJunior_Main_impl_log_info(myJunior_Main_impl__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYJUNIOR_MAIN_IMPL, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYJUNIOR_MAIN_IMPL, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myJunior_Main_impl_container__log_info(context, log);
}

void myJunior_Main_impl_log(myJunior_Main_impl__context* context, char *msg, ...) {
    ECOA__log log;
    strncpy(log.data, MYJUNIOR_MAIN_IMPL, ECOA__LOG_MAXSIZE);
    va_list argp;
    va_start(argp, msg);
    vsnprintf((char *) log.data + strnlen(MYJUNIOR_MAIN_IMPL, ECOA__LOG_MAXSIZE),
    ECOA__LOG_MAXSIZE, msg, argp);
    va_end(argp);
    log.current_size = strnlen((char *) &log.data, ECOA__LOG_MAXSIZE);
    myJunior_Main_impl_container__log_debug(context, log);
}



void myJunior_Main_impl__set_information(myJunior_Main_impl__context *context,
        libmarx__T_Data* data) {
    myJunior_Main_impl_container__information_handle handle;

    ECOA__return_status return_status;

    return_status =
            myJunior_Main_impl_container__information__get_write_access(
                    context, &handle);

    if (return_status == ECOA__return_status_OK
            || return_status == ECOA__return_status_DATA_NOT_INITIALIZED) {

        *(handle.data) = *data;

        return_status =
                myJunior_Main_impl_container__information__publish_write_access(
                        context, &handle);

        if (return_status != ECOA__return_status_OK) {
            myJunior_Main_impl_log(context,
                    "information: publish_write_access FAILED / error = %d", return_status);
        }
    } else {
        myJunior_Main_impl_log(context,
                "information: get_write_access FAILED / error = %d", return_status);
    }
}



