/* Module Test Container Implementation Skeleton for myJunior_Main_impl */

/* @file myJunior_Main_impl_test_container.c
 * This is the Module Test Container for Module myJunior_Main_impl
 * This file is generated by the ECOA tools and shall not be modified
 */

/* Generated by PARSEC */

#include <stdlib.h>

#include "ECOA.h"
#include "myJunior_Main_impl_container.h"

#include "ECOA.h"
#include "libmarx.h"

void myJunior_Main_impl_container__notification__send(myJunior_Main_impl__context* context, const libmarx__T_Data* param)
{
  /* @TODO TODO - To be implemented */
}

ECOA__return_status myJunior_Main_impl_container__transaction__response_send(myJunior_Main_impl__context* context, const ECOA__uint32 ID, libmarx__T_Data* output)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;  return return_status;}

ECOA__return_status myJunior_Main_impl_container__information__get_write_access(myJunior_Main_impl__context* context, myJunior_Main_impl_container__information_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  data_handle->data = malloc(sizeof(libmarx__T_Data));
  return return_status;
}

ECOA__return_status myJunior_Main_impl_container__information__cancel_write_access(myJunior_Main_impl__context* context, myJunior_Main_impl_container__information_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

ECOA__return_status myJunior_Main_impl_container__information__publish_write_access(myJunior_Main_impl__context* context, myJunior_Main_impl_container__information_handle* data_handle)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  free(data_handle->data);
  return return_status;
}


/* Properties API */

/* Logging services API call specifications */
void myJunior_Main_impl_container__log_trace(myJunior_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myJunior_Main_impl_container__log_debug(myJunior_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myJunior_Main_impl_container__log_info(myJunior_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myJunior_Main_impl_container__log_warning(myJunior_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myJunior_Main_impl_container__raise_error(myJunior_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}

void myJunior_Main_impl_container__raise_fatal_error(myJunior_Main_impl__context* context, const ECOA__log log)
{
  /* @TODO TODO - To be implemented */
}


/* Recovery action service API call specification if the module is a Fault Handler */

/* Time Services API call specifications */
void myJunior_Main_impl_container__get_relative_local_time(myJunior_Main_impl__context* context, ECOA__hr_time *relative_local_time)
{
  /* @TODO TODO - To be implemented */
}

ECOA__return_status myJunior_Main_impl_container__get_UTC_time(myJunior_Main_impl__context* context, ECOA__global_time *utc_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

ECOA__return_status myJunior_Main_impl_container__get_absolute_system_time(myJunior_Main_impl__context* context, ECOA__global_time *absolute_system_time)
{
  /* @TODO TODO - To be implemented */
  ECOA__return_status return_status = ECOA__return_status_OK;
  return return_status;
}

void myJunior_Main_impl_container__get_relative_local_time_resolution(myJunior_Main_impl__context* context, ECOA__duration *relative_local_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myJunior_Main_impl_container__get_UTC_time_resolution(myJunior_Main_impl__context* context, ECOA__duration *utc_time_resolution)
{
  /* @TODO TODO - To be implemented */
}

void myJunior_Main_impl_container__get_absolute_system_time_resolution(myJunior_Main_impl__context* context, ECOA__duration *absolute_system_time_resolution)
{
  /* @TODO TODO - To be implemented */
}


