/* Generated by PARSEC */
/* Module User Context Header for module myDemoPong_mod */
#if !defined(__MYDEMOPONG_MOD_USER_CONTEXT_H__)
#define __MYDEMOPONG_MOD_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPong_mod_user_context.h
 */

#include "lib_array.h"
/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/
	int nb_ping;
  /*********** USER ***********/
} myDemoPong_mod_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myDemoPong_mod_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYDEMOPONG_MOD_USER_CONTEXT_H__ */
