/*******************************************************/
/*
 * Generated by : PARSEC 5.1.1 
 */
/*
 * Copyright Dassault Aviation 
 */
/*
 * date: 2021-10-28 17:32:58.484079 
 */
/*******************************************************/


/*
 * Module User Context Header for module myElder_Main_impl 
 */
#if !defined(_MYELDER_MAIN_IMPL_USER_CONTEXT_H)
#define _MYELDER_MAIN_IMPL_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C"
{
#endif

  /*
   * @file myElder_Main_impl_user_context.h
   */

#include "ECOA.h"
#include "libmarx.h"
  /*
   * Module User Context Structure 
   */
  typedef struct
  {
    /*********** START USER-WRITTEN USER ***********/

    ECOA__uint32 id;
    libmarx__T_PositiveInteger notification_number;
    libmarx__T_PositiveInteger counter;
    libmarx__T_Data data;
    ECOA__boolean8 pinfo_test_flag;
    ECOA__boolean8 log_test_flag;
    ECOA__boolean8 time_test_flag;

    /*********** END USER-WRITTEN USER ***********/
  } myElder_Main_impl_user_context;


  /*
   * Warm start Module Context structure 
   */
  typedef struct
  {
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
  } myElder_Main_impl_warm_start_context;

#if defined(__cplusplus)
}
#endif
#endif                          /* _MYELDER_MAIN_IMPL_USER_CONTEXT_H */
