/* Generated by PARSEC */
/* Module User Context Header for module myCompWriter_mod0 */
#if !defined(_MYCOMPWRITER_MOD0_USER_CONTEXT_H)
#define _MYCOMPWRITER_MOD0_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myCompWriter_mod0_user_context.h
 */

#include "VD_lib.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/

    /*********** START USER-WRITTEN USER ***********/
} myCompWriter_mod0_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myCompWriter_mod0_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYCOMPWRITER_MOD0_USER_CONTEXT_H */
