/* Generated by PARSEC */
/* Module User Context Header for module myCompFinisher_mod */
#if !defined(_MYCOMPFINISHER_MOD_USER_CONTEXT_H)
#define _MYCOMPFINISHER_MOD_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myCompFinisher_mod_user_context.h
 */

#include "ECOA.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
	int num_msg;
    /*********** START USER-WRITTEN USER ***********/
} myCompFinisher_mod_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myCompFinisher_mod_warm_start_context;

#if defined(__cplusplus)
}
#endif

#endif  /* _MYCOMPFINISHER_MOD_USER_CONTEXT_H */
