/* Generated by PARSEC */
/* Module User Context Header for module myEarth_mod_impl */
#if !defined(_MYEARTH_MOD_IMPL_USER_CONTEXT_H)
#define _MYEARTH_MOD_IMPL_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myEarth_mod_impl_user_context.h
 */

#include "ECOA.h"
#include "myLib.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/

    /*********** START USER-WRITTEN USER ***********/
} myEarth_mod_impl_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myEarth_mod_impl_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYEARTH_MOD_IMPL_USER_CONTEXT_H */
