/* Generated by PARSEC */
/* Module Implementation myDemoServer_AM */

#include "ECOA.h"
#include "myDemoServer_AM.h"

#include "pingpong.h"

#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include "assert.h"


int myDemoServer_AM_log_trace(myDemoServer_AM__context* context, const char *msg, ...) {
  ECOA__log log;
  va_list argp;
  va_start(argp, msg);
  vsnprintf((char *)&log.data, ECOA__LOG_MAXSIZE, msg, argp);
  va_end(argp);
  log.current_size = strnlen((char *)&log.data, ECOA__LOG_MAXSIZE);
  myDemoServer_AM_container__log_trace(context, log);
  return log.current_size;
}

/* Entry points for lifecycle operations */
void myDemoServer_AM__INITIALIZE__received(myDemoServer_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_AM__REINITIALIZE__received(myDemoServer_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_AM__START__received(myDemoServer_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_AM__STOP__received(myDemoServer_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_AM__SHUTDOWN__received(myDemoServer_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoServer_AM__req_Sync__request_received(myDemoServer_AM__context* context, const ECOA__uint32 ID)
{
  /* @TODO TODO - To be implemented */
	myDemoServer_AM_log_trace(context,"received req Sync interne ID=%i", ID);
	usleep(5*1000*100);
  // send with timeout
	myDemoServer_AM_container__req_Sync__response_send(context, ID);
  myDemoServer_AM_container__finish__send(context);
}

void myDemoServer_AM__req_Async__request_received(myDemoServer_AM__context* context, const ECOA__uint32 ID)
{
  /* @TODO TODO - To be implemented */
	myDemoServer_AM_log_trace(context,"received req Async interne ID=%i", ID);
  usleep(5*1000*100);
  // send with timeout
	assert(myDemoServer_AM_container__req_Async__response_send(context, ID) == ECOA__return_status_OK);
  myDemoServer_AM_container__finish__send(context);
}

