/* Generated by PARSEC */
/* Module Implementation myDemoPing_AM */

#include "ECOA.h"
#include "myDemoPing_AM.h"

#include "ECOA.h"
#include "libRoot.h"
#include "libRoot__level1A.h"

#include "LDP__libRoot_types_zeroise.h"
#include "LDP__libRoot__level1A_types_zeroise.h"
#include "LDP__libRoot_types_compare.h"
#include "LDP__libRoot__level1A_types_compare.h"
#include "LDP_myDemoPing_AM.h"
#include "unistd.h"

#include "assert.h"

/* Entry points for lifecycle operations */
void myDemoPing_AM__INITIALIZE__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__START__received(myDemoPing_AM__context* context)
{
	libRoot__array_1A in_param3;
	libRoot__level1A__simple1B out_param1;
	ECOA__uint32 out_param2;
	libRoot__array_1A out_param3;
	ECOA__boolean8 out_bool;
	while(LDP_myDemoPing_AM__request_sync__sync_req(context , 3, 14, &in_param3, &out_param1, &out_param2, &out_param3, &out_bool) != ECOA__return_status_OK){
		sleep(1);
	}

	assert(out_param1 == 3);
	assert(out_param2 == 14);
	assert(out_bool);
	ECOA__uint32 ID;
	assert(LDP_myDemoPing_AM__request_async__async_req(context, &ID , 4, 15, &in_param3) == ECOA__return_status_OK);

}

void myDemoPing_AM__STOP__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__SHUTDOWN__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__external_event__received(myDemoPing_AM__context* context, const libRoot__level1A__simple1B param1, const ECOA__uint32 param2, const libRoot__array_1A* param3)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__async_req__response_received(myDemoPing_AM__context* context, const ECOA__uint32 ID, const ECOA__return_status status, const libRoot__level1A__simple1B out_param1, const ECOA__uint32 out_param2, const libRoot__array_1A* out_param3, const ECOA__boolean8 out_bool)
{
	assert(status == ECOA__return_status_OK);
	assert(out_param1 == 4);
	assert(out_param2 == 15);
	assert(!out_bool);

	LDP_myDemoPing_AM__send__event_sent(context, out_param1, out_param2, out_param3);
}

