/* Generated by PARSEC */
/* Module Implementation myCompWriter_mod */

#include "ECOA.h"
#include "myCompWriter_mod.h"

#include "ECOA.h"
#include "VD_lib.h"
#include "assert.h"

/* Entry points for lifecycle operations */
void myCompWriter_mod__INITIALIZE__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod__START__received(myCompWriter_mod__context* context)
{
	context->user.write_num = 1;

	// init write
	myCompWriter_mod_container__write_vector_handle data_handle;

	assert(myCompWriter_mod_container__write_vector__get_write_access(context, &data_handle) == ECOA__return_status_DATA_NOT_INITIALIZED);
	data_handle.data->writter_0 = 1;
	data_handle.data->writter_1 = 0;
	data_handle.data->writter_2 = 0;
	data_handle.data->writter_3 = 0;
	assert( myCompWriter_mod_container__write_vector__publish_write_access(context, &data_handle) == ECOA__return_status_OK);
}

void myCompWriter_mod__STOP__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod__SHUTDOWN__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod__trigger__received(myCompWriter_mod__context* context)
{
	myCompWriter_mod_container__write_vector_handle data_handle;

	if(context->user.write_num == 10){
		myCompWriter_mod_container__finish__send(context);
	}

	assert(myCompWriter_mod_container__write_vector__get_write_access(context, &data_handle) == ECOA__return_status_OK);
	assert(data_handle.data->writter_0 == 1);
	assert(data_handle.data->writter_1 == 0);
	assert(data_handle.data->writter_2 == 0);
	assert(data_handle.data->writter_3 == 0);

	context->user.write_num++;

	// not writte to avoid averwritting in Reader_comp
	assert( myCompWriter_mod_container__write_vector__cancel_write_access(context, &data_handle) == ECOA__return_status_OK);

}

