/* Generated by PARSEC */
/* Module User Context Header for module myReader_mod */
#if !defined(_MYREADER_MOD_USER_CONTEXT_H)
#define _MYREADER_MOD_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myReader_mod_user_context.h
 */

#include "ECOA.h"
#include "VD_lib.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/

    /*********** START USER-WRITTEN USER ***********/
} myReader_mod_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myReader_mod_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYREADER_MOD_USER_CONTEXT_H */
