/* Generated by PARSEC */
/* Module User Context Header for module myDemoServer2_AM */
#if !defined(__MYDEMOSERVER2_AM_USER_CONTEXT_H__)
#define __MYDEMOSERVER2_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoServer2_AM_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/

  /*********** USER ***********/
} myDemoServer2_AM_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myDemoServer2_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYDEMOSERVER2_AM_USER_CONTEXT_H__ */
