/* Generated by PARSEC */
/* Module Implementation myDemoPong_mod */

#include "ECOA.h"
#include "myDemoPong_mod.h"

#include "lib_array.h"
#include <stdio.h>
#include <stdarg.h>
#include <assert.h>

static void print_log(myDemoPong_mod__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myDemoPong_mod_container__log_trace(context, log);
}

static int check_array(myDemoPong_mod__context* context, const ECOA__uint32* array, int size_array){
  if (array[size_array-1] != 0xEC0A){
      print_log(context, "ERROR [run %i] last element is invalide, %i != 0xECOA",context->user.nb_ping_received, array[size_array-1] );
    return -1;
  }
  ECOA__uint32 val = array[0] - 0XEC0A;

  for(int i=1; i < size_array -1 ; i++){
    if((array)[i] != i + val){
      print_log(context, "ERROR [run %i] index : %i, %i != %i",context->user.nb_ping_received, i, (array)[i], i + val );
      return -1;
    }
  }
  return 0;
}

/* Entry points for lifecycle operations */
void myDemoPong_mod__INITIALIZE__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__REINITIALIZE__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__START__received(myDemoPong_mod__context* context)
{
  context->user.nb_ping_received = 0;
}

void myDemoPong_mod__STOP__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__SHUTDOWN__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__Ping_array_1k__request_received(myDemoPong_mod__context* context, const ECOA__uint32 ID, const lib_array__array_1k* array)
{
  context->user.nb_ping_received++;
  print_log(context, "ping %i 1k", context->user.nb_ping_received);
  int ret = check_array(context, (ECOA__uint32*) array, lib_array__array_1k_MAXSIZE);
  assert(ret == 0);
  ret = myDemoPong_mod_container__Ping_array_1k__response_send(context,ID);
  assert(ret == ECOA__return_status_OK);
}

void myDemoPong_mod__Ping_array_4k__request_received(myDemoPong_mod__context* context, const ECOA__uint32 ID, const lib_array__array_4k* array)
{
  context->user.nb_ping_received++;
  print_log(context, "ping %i 4k", context->user.nb_ping_received);
  int ret = myDemoPong_mod_container__Ping_array_4k__response_send(context,ID) ;
    assert(ret== ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) array, lib_array__array_4k_MAXSIZE);
  assert(ret == 0);
}

void myDemoPong_mod__Ping_array_256k__request_received(myDemoPong_mod__context* context, const ECOA__uint32 ID, const lib_array__array_256k* array)
{
  context->user.nb_ping_received++;
  print_log(context, "ping %i 256k", context->user.nb_ping_received);
  int ret = myDemoPong_mod_container__Ping_array_256k__response_send(context,ID);
  assert(ret == ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) array, lib_array__array_256k_MAXSIZE);
  assert(ret == 0);
}

void myDemoPong_mod__Ping_array_16k__request_received(myDemoPong_mod__context* context, const ECOA__uint32 ID, const lib_array__array_16k* array)
{
  context->user.nb_ping_received++;
  print_log(context, "ping %i 16k", context->user.nb_ping_received);
  int ret = myDemoPong_mod_container__Ping_array_16k__response_send(context,ID);
  assert(ret == ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) array, lib_array__array_16k_MAXSIZE);
  assert(ret == 0);
}

void myDemoPong_mod__Ping_array_64k__request_received(myDemoPong_mod__context* context, const ECOA__uint32 ID, const lib_array__array_64k* array)
{
  context->user.nb_ping_received++;
  print_log(context, "ping %i 64k", context->user.nb_ping_received);
  int ret = myDemoPong_mod_container__Ping_array_64k__response_send(context,ID) ;
    assert(ret== ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) array, lib_array__array_64k_MAXSIZE);
  assert(ret == 0);
}

void myDemoPong_mod__Ping_array_10m__request_received(myDemoPong_mod__context* context, const ECOA__uint32 ID, const lib_array__array_10m* array)
{
  context->user.nb_ping_received++;
  print_log(context, "ping %i 10m", context->user.nb_ping_received);
  int ret = myDemoPong_mod_container__Ping_array_10m__response_send(context,ID);
  assert(ret == ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) array, lib_array__array_10m_MAXSIZE);
  assert(ret == 0);
}