/* Generated by PARSEC */
/* Module Implementation mySender_AM */
#include <stdio.h>
#include "ECOA.h"
#include "mySender_AM.h"
#include <stdarg.h>
#include <apr_time.h>

static void print_log(mySender_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  mySender_AM_container__log_trace(context, log);
}


void mySender_AM__INITIALIZE__received(mySender_AM__context* context)
{
   /* One-shot initialisation activities: */
   /* @TODO TODO - To be implemented */

   /* Call REINITIALIZE entry-point: */
}

void mySender_AM__REINITIALIZE__received(mySender_AM__context* context)
{
   /* @TODO TODO - To be implemented */
}

void mySender_AM__START__received(mySender_AM__context* context)
{
   /* @TODO TODO - To be implemented */
	print_log(context, "START");
  apr_sleep(200000);
	mySender_AM_container__Ping__send(context);
}

void mySender_AM__STOP__received(mySender_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void mySender_AM__SHUTDOWN__received(mySender_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}
