/* Generated by PARSEC */
/* Module Implementation myCompReader_mod */

#include "ECOA.h"
#include "myCompReader_mod.h"

#include "ECOA.h"
#include "VD_lib.h"
#include <assert.h>

/* Entry points for lifecycle operations */
void myCompReader_mod__INITIALIZE__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod__START__received(myCompReader_mod__context* context)
{
	context->user.num_vector0 = 0;
	context->user.num_vector1 = 0;
}

void myCompReader_mod__STOP__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompReader_mod__SHUTDOWN__received(myCompReader_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

	void myCompReader_mod__read_vector0__updated(myCompReader_mod__context* context){

	myCompReader_mod_container__read_vector0_handle data_handle;
	assert(myCompReader_mod_container__read_vector0__get_read_access(context, &data_handle) == ECOA__return_status_OK);
	printf("received 0: %i %i\n", data_handle.data->nb_x, data_handle.data->nb_y);
	assert(myCompReader_mod_container__read_vector0__release_read_access(context, &data_handle) == ECOA__return_status_OK);

	context->user.num_vector0++;
	if(context->user.num_vector0 == 30){
		myCompReader_mod_container__finish__send(context);
	}
}

void myCompReader_mod__read_vector1__updated(myCompReader_mod__context* context){
	myCompReader_mod_container__read_vector1_handle data_handle;
	assert(myCompReader_mod_container__read_vector1__get_read_access(context, &data_handle) == ECOA__return_status_OK);
	printf("received 1: %i %i\n", data_handle.data->nb_x, data_handle.data->nb_y);
	assert( data_handle.data->nb_x <= data_handle.data->nb_y+1); // x == y or x == y+1
	assert(myCompReader_mod_container__read_vector1__release_read_access(context, &data_handle) == ECOA__return_status_OK);

	context->user.num_vector1++;
	if(context->user.num_vector1 == 30){
		myCompReader_mod_container__finish__send(context);
	}
}

