/* Generated by PARSEC */
/* Module User Context Header for module myDemoServer_L2_AM */
#if !defined(__MYDEMOSERVER_L2_AM_USER_CONTEXT_H__)
#define __MYDEMOSERVER_L2_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoServer_L2_AM_user_context.h
 */

/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/
	int nb_of_pong;

  /*********** USER ***********/
} myDemoServer_L2_AM_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myDemoServer_L2_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYDEMOSERVER_L2_AM_USER_CONTEXT_H__ */
