/* Generated by PARSEC */
/* Module Implementation myCompWriter_mod0 */

#include "ECOA.h"
#include "myCompWriter_mod0.h"

#include "VD_lib.h"

#include <string.h>
#include <assert.h>
#include <unistd.h>
#include <stdio.h>

/* Entry points for lifecycle operations */
void myCompWriter_mod0__INITIALIZE__received(myCompWriter_mod0__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod0__REINITIALIZE__received(myCompWriter_mod0__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod0__START__received(myCompWriter_mod0__context* context)
{
  VD_lib__vector_data new_vector={0,0,0};
  VD_lib__vector_data old_vector={0,0,0};
  myCompWriter_mod0_container__write_vector_handle handle;

  while(1){
  	ECOA__return_status ret = myCompWriter_mod0_container__write_vector__get_write_access(context, &handle);
  	if(ret == ECOA__return_status_DATA_NOT_INITIALIZED){
  		// first write
  		printf("first write\n");
  		new_vector.nb_x = -33;
  		new_vector.nb_y = 33;
      myCompWriter_mod0_container__get_writer_id_value(context, &new_vector.writer_id);
  	}else{
  		assert(ret == ECOA__return_status_OK);

      	memcpy(&new_vector,handle.data,sizeof(VD_lib__vector_data) );
  		assert( new_vector.nb_x == old_vector.nb_x);
  		assert( new_vector.nb_y == old_vector.nb_y);

  		new_vector.nb_x++;
  		new_vector.nb_y--;
  	}

  	memcpy(handle.data, &new_vector,sizeof(VD_lib__vector_data) );
  	old_vector = new_vector;

	ret=myCompWriter_mod0_container__write_vector__publish_write_access(context, &handle);
	assert(ret == ECOA__return_status_OK);

	if(new_vector.nb_x == new_vector.nb_y)
		break;

  	usleep(10000);
  }
  printf("writer finish\n");
  myCompWriter_mod0_container__finish__send(context);
  assert(1);

}

void myCompWriter_mod0__STOP__received(myCompWriter_mod0__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod0__SHUTDOWN__received(myCompWriter_mod0__context* context)
{
  /* @TODO TODO - To be implemented */
}

