/* Generated by PARSEC */
/* Module User Context Header for module mydemoServer0_AM */
#if !defined(__MYDEMOSERVER0_AM_USER_CONTEXT_H__)
#define __MYDEMOSERVER0_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file mydemoServer0_AM_user_context.h
 */

/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/

  /*********** USER ***********/
} mydemoServer0_AM_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} mydemoServer0_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYDEMOSERVER0_AM_USER_CONTEXT_H__ */
