/* Generated by PARSEC */
/* Module Implementation mydemoClient0_AM */

#include "ECOA.h"
#include "../inc-gen/mydemoClient0_AM.h"
#include <stdio.h>

#include "mylib.h"
#include <stdarg.h>

static void print_log(mydemoClient0_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  mydemoClient0_AM_container__log_trace(context, log);
}

/* Entry points for lifecycle operations */
void mydemoClient0_AM__INITIALIZE__received(mydemoClient0_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void mydemoClient0_AM__REINITIALIZE__received(mydemoClient0_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void mydemoClient0_AM__START__received(mydemoClient0_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void mydemoClient0_AM__STOP__received(mydemoClient0_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void mydemoClient0_AM__SHUTDOWN__received(mydemoClient0_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void mydemoClient0_AM__Ping00__received(mydemoClient0_AM__context* context)
{
  /* @TODO TODO - To be implemented */
	print_log(context, "          Ping00");
	mydemoClient0_AM_container__Hello0__send(context);
}

