/* Generated by PARSEC */
/* Module User Context Header for module myDemoMain2_AM */
#if !defined(__MYDEMOMAIN2_AM_USER_CONTEXT_H__)
#define __MYDEMOMAIN2_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoMain2_AM_user_context.h
 */

/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/

  /*********** USER ***********/
} myDemoMain2_AM_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myDemoMain2_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYDEMOMAIN2_AM_USER_CONTEXT_H__ */
