/* Generated by PARSEC */
/* Module Implementation myDemoPing_AM */

#include "ECOA.h"

#include "lib.h"
#include "ldp_structures.h"
#include "apr_strings.h"
#include <assert.h>
#include "pingpong.h"
#include "LDP__pingpong_types_zeroise.h"
#include "math.h"
#include "myDemoPing_AM.h"
/* Entry points for lifecycle operations */
void myDemoPing_AM__INITIALIZE__received(myDemoPing_AM__context* context)
{
// test default values function
    pingpong__Simple1 data__Simple1;
    LDP_pingpong__Simple1_zeroise(&data__Simple1);assert(data__Simple1 == ECOA__UINT32_MIN);
    pingpong__Simple2 data__Simple2;
    LDP_pingpong__Simple2_zeroise(&data__Simple2);assert(data__Simple2 == ECOA__FLOAT32_MIN);
    pingpong__Simple2 data__Simple3;
    LDP_pingpong__Simple3_zeroise(&data__Simple3);assert(data__Simple3 - 100.0 < 0.0001);
    pingpong__Enum1 data_Enum1;
    LDP_pingpong__Enum1_zeroise(&data_Enum1);assert(data_Enum1 == pingpong__Enum1_PONG);
    pingpong__Enum2 data_Enum2;
    LDP_pingpong__Enum2_zeroise(&data_Enum2);assert(data_Enum2 == 12);

    pingpong__Record1 data_Record1;
    LDP_pingpong__Record1_zeroise(&data_Record1);
    assert(data_Record1.Rec_field1 == ECOA__UINT32_MIN);
    assert(data_Record1.Rec_field2 == ECOA__UINT32_MIN);
    assert(data_Record1.Rec_field3 == 12);
    assert(data_Record1.Rec_field4 - 100.0 < 0.0001);

    pingpong__VarRecord1 data_VarRecord1;
    LDP_pingpong__VarRecord1_zeroise(&data_VarRecord1);
    assert(data_VarRecord1.Selector == pingpong__Enum2_PING);
    assert(data_VarRecord1.u_Selector.int_Sunday == ECOA__CHAR8_MIN);

    pingpong__VarRecord2 data_VarRecord2;
    LDP_pingpong__VarRecord2_zeroise(&data_VarRecord2);
    assert(data_VarRecord2.Selector == 1);
    assert(data_VarRecord2.u_Selector.int_Sunday == 0);

    pingpong__my_message msg1;
    LDP_pingpong__my_message_zeroise(&msg1);
    assert(msg1.current_size == 0);

    pingpong__my_message_f msg2;
    LDP_pingpong__my_message_f_zeroise(&msg2);
    for (int i=0; i < pingpong__my_message_f2_MAXSIZE;i++){
        assert(msg2[i].Rec_field1 == ECOA__UINT32_MIN);
        assert(msg2[i].Rec_field2 == ECOA__UINT32_MIN);
        assert(msg2[i].Rec_field3 == pingpong__Constante1);
        assert(abs(msg2[i].Rec_field4 - ECOA__FLOAT32_MIN) < 0.00001);
    }

    pingpong__my_message_f2 msg3;
    LDP_pingpong__my_message_f2_zeroise(&msg3);
    for (int i=0; i < pingpong__my_message_f2_MAXSIZE;i++){
        assert(msg3[i] == pingpong__Simple3_minRange);
    }

}

void myDemoPing_AM__REINITIALIZE__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__START__received(myDemoPing_AM__context* context)
{
    ldp_module_context* ctx=(ldp_module_context*) context->platform_hook;

    // component level
    ECOA__uint32 comp_prop1;
    myDemoPing_AM_container__get_m_ref_comp_prop1_value(context, &comp_prop1);
    if(apr_strnatcmp (ctx->component_name, "demoPingPong_0") == 0){
        assert(comp_prop1 == 10);
    }else if(apr_strnatcmp (ctx->component_name, "demoPingPong_1") == 0 ){
        assert(comp_prop1 == 11);
    }else{
        assert(0);
    }

    // module instance level
    ECOA__float32 float_prop;
    myDemoPing_AM_container__get_m_float_prop_value(context, &float_prop);

    lib__Test_array array;
    myDemoPing_AM_container__get_m_ref_ass_array_value(context, &array);
    assert(array.current_size == 5);
    if(apr_strnatcmp (ctx->name, "myDemoPing_AM_I_0") == 0){
        assert(float_prop - 10.0 < 0.000001);
        for (int i = 0; i<array.current_size; i++){
            assert( array.data[i] == i);
        }
    }else if(apr_strnatcmp (ctx->name, "myDemoPing_AM_I_1") == 0 ){
        assert(float_prop - 11.0 < 0.000001);
        for (int i = 0; i<array.current_size; i++){
            assert( array.data[i] == 42);
        }
    }else{
        assert(0);
    }

    apr_sleep(200000);
    myDemoPing_AM_container__Ping__send(context);
}

void myDemoPing_AM__STOP__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__SHUTDOWN__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_AM__Pong__received(myDemoPing_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

