/* Generated by PARSEC */
/* Module Implementation myDemoFinish_mod_impl */

#include "ECOA.h"
#include "myDemoFinish_mod_impl.h"

#include "pingpong.h"
#include "ldp_structures.h"
#include "ldp_mod_container_util.h"
#include <stdio.h>
#include <stdarg.h>


static void print_log(myDemoFinish_mod_impl__context* context, const char *format, ...){
	va_list vl;
	ECOA__log log;

	va_start(vl, format);
	vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
	va_end( vl);

	myDemoFinish_mod_impl_container__log_trace(context, log);
}

/* Entry points for lifecycle operations */
void myDemoFinish_mod_impl__INITIALIZE__received(myDemoFinish_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_mod_impl__START__received(myDemoFinish_mod_impl__context* context)
{
	context->user.finish_num = 0;
}

void myDemoFinish_mod_impl__STOP__received(myDemoFinish_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_mod_impl__SHUTDOWN__received(myDemoFinish_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_mod_impl__finish__received(myDemoFinish_mod_impl__context* context)
{	context->user.finish_num++;
	if(context->user.finish_num == 4){
		print_log(context, "\033[1;32m SUCCESS \033[0m");
		ldp_kill_platform((ldp_module_context*)context->platform_hook);
	}
}

