/* Generated by PARSEC */
/* Module User Context Header for module myDemoServer_mod_impl */
#if !defined(_MYDEMOSERVER_MOD_IMPL_USER_CONTEXT_H)
#define _MYDEMOSERVER_MOD_IMPL_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoServer_mod_impl_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/

    /*********** START USER-WRITTEN USER ***********/
} myDemoServer_mod_impl_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myDemoServer_mod_impl_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* _MYDEMOSERVER_MOD_IMPL_USER_CONTEXT_H */
