/* Generated by PARSEC */
/* Module User Context Header for module myCompWriter_mod */
#if !defined(_MYCOMPWRITER_MOD_USER_CONTEXT_H)
#define _MYCOMPWRITER_MOD_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myCompWriter_mod_user_context.h
 */

#include "ECOA.h"
#include "VD_lib.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
    int write_num;
    /*********** START USER-WRITTEN USER ***********/
} myCompWriter_mod_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myCompWriter_mod_warm_start_context;

#if defined(__cplusplus)
}
#endif

#endif  /* _MYCOMPWRITER_MOD_USER_CONTEXT_H */
