/* Generated by PARSEC */
/* Module Implementation myDemoPong_mod */

#include "ECOA.h"
#include "myDemoPong_mod.h"

#include "lib_array.h"
#include <assert.h>

#include <stdio.h>
#include <stdarg.h>

static void print_log(myDemoPong_mod__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myDemoPong_mod_container__log_trace(context, log);
}

static int check_array(myDemoPong_mod__context* context, const ECOA__uint32* array, int size_array){
  if (array[size_array-1] != 0xA0CE){
      print_log(context, "ERROR [run %i] last element is invalide, %i != 0XA0CE",context->user.nb_ping, array[size_array-1] );
    return -1;
  }
  ECOA__uint32 val = array[0] - 0XA0CE;

  for(int i=1; i < size_array -1 ; i++){
    if((array)[i] != i + val){

      print_log(context, "ERROR [run %i] index : %i, %i != %i",context->user.nb_ping, i, (array)[i], i + val );
      return -1;
    }
  }
  return 0;
}

/* Entry points for lifecycle operations */
void myDemoPong_mod__INITIALIZE__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
  context->user.nb_ping = 0;
}

void myDemoPong_mod__REINITIALIZE__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__START__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__STOP__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__SHUTDOWN__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__Ping_array_256k__received(myDemoPong_mod__context* context, const lib_array__array_256k* array)
{
  assert(check_array(context, (ECOA__uint32*) array, lib_array__array_256k_MAXSIZE) == 0);
  myDemoPong_mod_container__Pong__send(context);
  context->user.nb_ping++;
}

void myDemoPong_mod__Ping_array_1k__received(myDemoPong_mod__context* context, const lib_array__array_1k* array)
{
  assert(check_array(context, (ECOA__uint32*) array, lib_array__array_1k_MAXSIZE) == 0);
  myDemoPong_mod_container__Pong__send(context);
  context->user.nb_ping++;
}

void myDemoPong_mod__Ping_array_16k__received(myDemoPong_mod__context* context, const lib_array__array_16k* array)
{
  assert(check_array(context, (ECOA__uint32*) array, lib_array__array_16k_MAXSIZE) == 0);
  myDemoPong_mod_container__Pong__send(context);
  context->user.nb_ping++;
}

void myDemoPong_mod__Ping_array_4k__received(myDemoPong_mod__context* context, const lib_array__array_4k* array)
{
  assert(check_array(context, (ECOA__uint32*) array, lib_array__array_4k_MAXSIZE) == 0);
  myDemoPong_mod_container__Pong__send(context);
  context->user.nb_ping++;
}

void myDemoPong_mod__Ping_array_64k__received(myDemoPong_mod__context* context, const lib_array__array_64k* array)
{
  assert(check_array(context, (ECOA__uint32*) array, lib_array__array_64k_MAXSIZE) == 0);
  myDemoPong_mod_container__Pong__send(context);
  context->user.nb_ping++;
}

void myDemoPong_mod__Ping_array_10m__received(myDemoPong_mod__context* context, const lib_array__array_10m* array)
{
  assert(check_array(context, (ECOA__uint32*) array, lib_array__array_10m_MAXSIZE) == 0);
  myDemoPong_mod_container__Pong__send(context);
  context->user.nb_ping++;
}