/* Generated by PARSEC */
/* Module User Context Header for module myDemoFinish_AM */
#if !defined(_MYDEMOFINISH_AM_USER_CONTEXT_H)
#define _MYDEMOFINISH_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoFinish_AM_user_context.h
 */

#include "ECOA.h"
#include "lib_module.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
    int finish_count;
    /*********** START USER-WRITTEN USER ***********/
} myDemoFinish_AM_user_context;

#if defined(__cplusplus)
}
#endif

#endif  /* _MYDEMOFINISH_AM_USER_CONTEXT_H */
