/* Generated by PARSEC */
/* Module Implementation myDemoReceiver_AM */

#include <assert.h>

#include "ECOA.h"
#include "lib_module.h"

#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include "myDemoReceiver_AM.h"

static void print_log(myDemoReceiver_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myDemoReceiver_AM_container__log_trace(context, log);
}


/* Entry points for lifecycle operations */
void myDemoReceiver_AM__INITIALIZE__received(myDemoReceiver_AM__context* context)
{
  context->user.event_received         = 0x00;
  context->user.request_sync_received  = 0x00;
  context->user.request_async_received = 0x00;
  context->user.vd_notif_received      = 0x00;
}

void myDemoReceiver_AM__START__received(myDemoReceiver_AM__context* context)
{
  ECOA__uint32 property_identifier;
  myDemoReceiver_AM_container__get_module_identifier_value(context, &property_identifier);

  if(property_identifier == 0x04 ||property_identifier == 0x05){
    //try to read a not connected data
    myDemoReceiver_AM_container__read_data_handle handle;
    ECOA__return_status ret = myDemoReceiver_AM_container__read_data__get_read_access(context, &handle);
    assert(ret == ECOA__return_status_NO_DATA);
  }

}

void myDemoReceiver_AM__STOP__received(myDemoReceiver_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoReceiver_AM__SHUTDOWN__received(myDemoReceiver_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

static void check_finish(myDemoReceiver_AM__context* context) {
  if (context->user.request_async_received == 0x01 &&
      context->user.request_sync_received  == 0x01 &&
      context->user.event_received         == 0x01 &&
      context->user.vd_notif_received      == 0x01){
        myDemoReceiver_AM_container__Finish_Sent__send(context);
  }
}

void myDemoReceiver_AM__Request_Async_Received__request_received(myDemoReceiver_AM__context* context, const ECOA__uint32 ID, const ECOA__uint32 module_implementation_identifier)
{
  ECOA__uint32 property_identifier;
  myDemoReceiver_AM_container__get_module_identifier_value(context, &property_identifier);
  assert(property_identifier == 0x03);

  if (module_implementation_identifier == 0x01){
    context->user.request_async_received = 0x01;
    print_log(context, "myDemoReceiver_AM__Request_Async_Received__received [RECEIVED] with identifier  [%d]", module_implementation_identifier);
  } else {
    print_log(context, "[ERROR] Received -- Request_Async_Received -- from module identifier [%d]", module_implementation_identifier);
    assert(0);
  }

  assert(myDemoReceiver_AM_container__Request_Async_Received__response_send(context, ID) == ECOA__return_status_OK);
  check_finish(context);
}

void myDemoReceiver_AM__Request_Sync_Received__request_received(myDemoReceiver_AM__context* context, const ECOA__uint32 ID, const ECOA__uint32 module_implementation_identifier)
{
  ECOA__uint32 property_identifier;
  myDemoReceiver_AM_container__get_module_identifier_value(context, &property_identifier);
  assert(property_identifier == 0x03);

  if (module_implementation_identifier == 0x01){
    context->user.request_sync_received = 0x01;
    print_log(context, "'myDemoReceiver_AM__Request_Sync_Received__received' [RECEIVED] with identifier [%d]", module_implementation_identifier);
  } else {
    print_log(context, "[ERROR] Received -- Request_Sync_Received -- from module identifier [%d]", module_implementation_identifier);
    assert(0);
  }

  assert(myDemoReceiver_AM_container__Request_Sync_Received__response_send(context, ID) == ECOA__return_status_OK);

  check_finish(context);
}

void myDemoReceiver_AM__Event_Received__received(myDemoReceiver_AM__context* context, const ECOA__uint32 module_implementation_identifier)
{
  ECOA__uint32 property_identifier;
  myDemoReceiver_AM_container__get_module_identifier_value(context, &property_identifier);
  assert(property_identifier == 0x03);

  if (module_implementation_identifier == 0x01){
    context->user.event_received = 0x01;
    print_log(context, "'myDemoReceiver_AM__Event_Received__received' [RECEIVED] with identifier  [%d]", module_implementation_identifier);
  } else {
    print_log(context, "[ERROR] Received -- Event_Received -- from module identifier [%d]", module_implementation_identifier);
    assert(0);
  }

  check_finish(context);
}

void myDemoReceiver_AM__read_data__updated(myDemoReceiver_AM__context* context)
{
  ECOA__uint32 property_identifier;
  myDemoReceiver_AM_container__get_module_identifier_value(context, &property_identifier);
  assert(property_identifier == 0x03);

  ECOA__uint32 data = 0x00;
  myDemoReceiver_AM_container__read_data_handle handle;

  ECOA__return_status ret = myDemoReceiver_AM_container__read_data__get_read_access(context, &handle);
  assert(ret == ECOA__return_status_OK);

  memcpy(&data,handle.data,sizeof(ECOA__uint32));

  if (data == 0x01 && context->user.vd_notif_received == 0x00){
    context->user.vd_notif_received = 0x01;
    check_finish(context);
  } else {
    assert(0);
  }

  ret = myDemoReceiver_AM_container__read_data__release_read_access(context, &handle);
  assert(ret == ECOA__return_status_OK);
}
