/* Generated by PARSEC */
/* Module Implementation myDemoPing_mod1_impl */

#include <assert.h>
#include "ECOA.h"

#include "pingpong.h"
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <apr_time.h>
#include "ldp_mod_container_util.h"
#include "myDemoPing_mod1_impl.h"


int myDemoPing_mod1_impl_log_trace(myDemoPing_mod1_impl__context* context, const char *msg, ...) {
  ECOA__log log;
  va_list argp;
  va_start(argp, msg);
  vsnprintf((char *)&log.data, ECOA__LOG_MAXSIZE, msg, argp);
  va_end(argp);
  log.current_size = strnlen((char *)&log.data, ECOA__LOG_MAXSIZE);
  myDemoPing_mod1_impl_container__log_trace(context, log);
  return log.current_size;
}

/* Entry points for lifecycle operations */
void myDemoPing_mod1_impl__INITIALIZE__received(myDemoPing_mod1_impl__context* context)
{
	context->user.nb_ping_response = 0;
}

void myDemoPing_mod1_impl__REINITIALIZE__received(myDemoPing_mod1_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_mod1_impl__START__received(myDemoPing_mod1_impl__context* context)
{
	apr_sleep(200000);

	ECOA__uint32 ID; pingpong__T_2D_Position Ping_Position;
	ECOA__uint32 ID2; pingpong__T_2D_Position Ping_Position2;
	ECOA__return_status ret = myDemoPing_mod1_impl_container__Ping_Sync__request_sync(context, &Ping_Position, 12, &Ping_Position2, &ID2);
	assert(ret == ECOA__return_status_NO_RESPONSE);
	context->user.nb_ping_response = 0;

	for (int i=0; i< 9;i++){
		ret = myDemoPing_mod1_impl_container__Ping_Async__request_async(context, &ID, &Ping_Position, 12);
		assert(ret == ECOA__return_status_OK);
	}
	ret = myDemoPing_mod1_impl_container__Ping_Async__request_async(context, &ID, &Ping_Position, 12);
	assert(ret == ECOA__return_status_RESOURCE_NOT_AVAILABLE);
	ret = myDemoPing_mod1_impl_container__Ping_Async__request_async(context, &ID, &Ping_Position, 12);
	assert(ret == ECOA__return_status_RESOURCE_NOT_AVAILABLE);
	ret = myDemoPing_mod1_impl_container__Ping_Async__request_async(context, &ID, &Ping_Position, 12);
	assert(ret == ECOA__return_status_RESOURCE_NOT_AVAILABLE);
	myDemoPing_mod1_impl_log_trace(context, "Send all requests");
}

void myDemoPing_mod1_impl__STOP__received(myDemoPing_mod1_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_mod1_impl__SHUTDOWN__received(myDemoPing_mod1_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPing_mod1_impl__Ping_Async__response_received(myDemoPing_mod1_impl__context* context, const ECOA__uint32 ID, const ECOA__return_status status, const pingpong__T_2D_Position* Pong_Position, const ECOA__uint32 Pong_Target)
{
	assert(status == ECOA__return_status_NO_RESPONSE);

	context->user.nb_ping_response++;
	myDemoPing_mod1_impl_log_trace(context, "	received Ping %i!! NO_RESPONSE", context->user.nb_ping_response);

	if(context->user.nb_ping_response==9){
		ldp_module_context* mod_ctx = (ldp_module_context*)context->platform_hook;
        assert(mod_ctx->req_resp.current_RR_number[0] == 0);
        assert(mod_ctx->req_resp.current_RR_number[1] == 0);

		myDemoPing_mod1_impl_log_trace(context, "\033[1;32m SUCCESS \033[0m");
		ldp_kill_platform((ldp_module_context*)context->platform_hook);
	}
}

