/* Generated by PARSEC */
/* Module User Context Header for module myDemoMessageReceiver_AM */
#if !defined(_MYDEMOMESSAGERECEIVER_AM_USER_CONTEXT_H)
#define _MYDEMOMESSAGERECEIVER_AM_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoMessageReceiver_AM_user_context.h
 */

#include "lib_array.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
    int _1k_received_count;
    int _4k_received_count;
    int _16k_received_count;
    int _64k_received_count;
    int _256k_received_count;
    int _10m_received_count;
    /*********** START USER-WRITTEN USER ***********/
} myDemoMessageReceiver_AM_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myDemoMessageReceiver_AM_warm_start_context;

#if defined(__cplusplus)
}
#endif

#endif  /* _MYDEMOMESSAGERECEIVER_AM_USER_CONTEXT_H */
