/* Generated by PARSEC */
/* Module Implementation myFinal_AM */

#include "ECOA.h"
#include "myFinal_AM.h"

#include "pingpong.h"
#include <stdio.h>
#include <unistd.h>
#include <time.h>
#include "ldp_mod_container_util.h"
#include <stdarg.h>

static void print_log(myFinal_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myFinal_AM_container__log_trace(context, log);
}


/* Entry points for lifecycle operations */
void myFinal_AM__INITIALIZE__received(myFinal_AM__context* context)
{
  /* @TODO TODO - To be implemented */
  context->user.nb=0;
}

void myFinal_AM__REINITIALIZE__received(myFinal_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myFinal_AM__START__received(myFinal_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myFinal_AM__STOP__received(myFinal_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myFinal_AM__SHUTDOWN__received(myFinal_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myFinal_AM__Finish__received(myFinal_AM__context* context)
{
  /* @TODO TODO - To be implemented */ 
  context->user.nb++;
  print_log(context, "Finish %i",context->user.nb);
  if(context->user.nb == 4){
      fflush(stdout);
      print_log(context, "\033[1;32m SUCCESS  \033[0m"); 
      ldp_kill_platform((ldp_module_context*)context->platform_hook);
  }
}

