/*******************************************************/
/* Generated by : PARSEC 5.0                           */
/*                Copyright Dassault Aviation          */
/*                date: 2019-03-04 11:44:35.288894     */
/*******************************************************/

/* Module User Context Header for module myCompWriter_write_only */
#if !defined(_MYCOMPWRITER_WRITE_ONLY_USER_CONTEXT_H)
#define _MYCOMPWRITER_WRITE_ONLY_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myCompWriter_write_only_user_context.h
 */

#include "ECOA.h"
#include "VD_lib.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
  VD_lib__vector_data vector;
    /*********** END USER-WRITTEN USER ***********/
} myCompWriter_write_only_user_context;


/* Warm start Module Context structure */
typedef struct
{
    /************* START USER-WRITTEN CODE *************/

    /*************** END USER-WRITTEN CODE *************/
} myCompWriter_write_only_warm_start_context;

#if defined(__cplusplus)
}
#endif

#endif  /* _MYCOMPWRITER_WRITE_ONLY_USER_CONTEXT_H */
