/* Generated by PARSEC */
/* Module Implementation myDemoPong_mod */

#include "ECOA.h"
#include "myDemoPong_mod.h"

#include "lib_array.h"
#include <assert.h>

#include <stdio.h>
#include <stdarg.h>

static void print_log(myDemoPong_mod__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myDemoPong_mod_container__log_trace(context, log);
}

static int check_array(myDemoPong_mod__context* context, const ECOA__uint32* array, int size_array){
  if (array[size_array-1] != 0xEC0A){
      print_log(context, "ERROR [run %i] last element is invalide, %i != 0xECOA",context->user.nb_ping_received, array[size_array-1] );
    return -1;
  }
  ECOA__uint32 val = array[0] - 0XEC0A;

  for(int i=1; i < size_array -1 ; i++){
    if((array)[i] != i + val){
      print_log(context, "ERROR [run %i] index : %i, %i != %i",context->user.nb_ping_received, i, (array)[i], i + val );
      return -1;
    }
  }
  return 0;
}

/* Entry points for lifecycle operations */
void myDemoPong_mod__INITIALIZE__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__REINITIALIZE__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__START__received(myDemoPong_mod__context* context)
{
  context->user.nb_ping_received = 0;
}

void myDemoPong_mod__STOP__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__SHUTDOWN__received(myDemoPong_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoPong_mod__Ping_array_1k__updated(myDemoPong_mod__context* context){
  context->user.nb_ping_received++;
  print_log(context,"Ping 1k");
  myDemoPong_mod_container__Ping_array_1k_handle data_handle;
  int ret = myDemoPong_mod_container__Ping_array_1k__get_read_access(context, &data_handle);
  assert( ret == ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) data_handle.data, lib_array__array_1k_MAXSIZE);
  assert( ret == 0);
  ret = myDemoPong_mod_container__Ping_array_1k__release_read_access(context, &data_handle);
  assert( ret == ECOA__return_status_OK);
  myDemoPong_mod_container__Pong__send(context);
}

void myDemoPong_mod__Ping_array_256k__updated(myDemoPong_mod__context* context){
  context->user.nb_ping_received++;
  print_log(context,"Ping 256k");
  myDemoPong_mod_container__Ping_array_256k_handle data_handle;
  int ret =  myDemoPong_mod_container__Ping_array_256k__get_read_access(context, &data_handle);
  assert(ret == ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) data_handle.data, lib_array__array_256k_MAXSIZE);
  assert(ret == 0);
  ret = myDemoPong_mod_container__Ping_array_256k__release_read_access(context, &data_handle);
  assert(ret == ECOA__return_status_OK);
  myDemoPong_mod_container__Pong__send(context);
}

void myDemoPong_mod__Ping_array_64k__updated(myDemoPong_mod__context* context){
  context->user.nb_ping_received++;
  print_log(context,"Ping 64k");
  myDemoPong_mod_container__Ping_array_64k_handle data_handle;
  int ret =  myDemoPong_mod_container__Ping_array_64k__get_read_access(context, &data_handle);
  assert(ret == ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) data_handle.data, lib_array__array_64k_MAXSIZE);
  assert(ret == 0);
  ret = myDemoPong_mod_container__Ping_array_64k__release_read_access(context, &data_handle);
  assert(ret == ECOA__return_status_OK);
  myDemoPong_mod_container__Pong__send(context);
}

void myDemoPong_mod__Ping_array_4k__updated(myDemoPong_mod__context* context){
  context->user.nb_ping_received++;
  print_log(context,"Ping 4k");
  myDemoPong_mod_container__Ping_array_4k_handle data_handle;
  int ret =  myDemoPong_mod_container__Ping_array_4k__get_read_access(context, &data_handle);
  assert(ret == ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) data_handle.data, lib_array__array_4k_MAXSIZE);
  assert(ret == 0);
  ret = myDemoPong_mod_container__Ping_array_4k__release_read_access(context, &data_handle);
  assert(ret== ECOA__return_status_OK);
  myDemoPong_mod_container__Pong__send(context);
}

void myDemoPong_mod__Ping_array_16k__updated(myDemoPong_mod__context* context){
  context->user.nb_ping_received++;
  print_log(context,"Ping 16k");
  myDemoPong_mod_container__Ping_array_16k_handle data_handle;
  int ret =  myDemoPong_mod_container__Ping_array_16k__get_read_access(context, &data_handle);
  assert(ret == ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) data_handle.data, lib_array__array_16k_MAXSIZE);
  assert(ret == 0);
  ret = myDemoPong_mod_container__Ping_array_16k__release_read_access(context, &data_handle);
  assert(ret == ECOA__return_status_OK);
  myDemoPong_mod_container__Pong__send(context);
}

void myDemoPong_mod__Ping_array_10m__updated(myDemoPong_mod__context* context){
  context->user.nb_ping_received++;
  print_log(context,"Ping10mk");
  myDemoPong_mod_container__Ping_array_10m_handle data_handle;
  int ret =  myDemoPong_mod_container__Ping_array_10m__get_read_access(context, &data_handle);
  assert(ret == ECOA__return_status_OK);
  ret = check_array(context, (ECOA__uint32*) data_handle.data, lib_array__array_10m_MAXSIZE);
  assert(ret == 0);
  ret = myDemoPong_mod_container__Ping_array_10m__release_read_access(context, &data_handle);
  assert(ret == ECOA__return_status_OK);
  myDemoPong_mod_container__Pong__send(context);
}