# -*- coding: utf-8 -*-
# Copyright (c) 2023 Dassault Aviation
# SPDX-License-Identifier: MIT

from importlib import metadata
__version__ = metadata.version("ecoa_ldp")
import datetime

def _version_string():
    version_string = __version__
    for i in range(0, len("#VERSION#") - len(__version__)):
        version_string += " "

    return version_string

def __generate_date():
    return str(datetime.datetime.now())

def generate_ldp_version_header():
    header="\
/**\n\
* Copyright (c) 2023 Dassault Aviation\n\
*\n\
* SPDX-License-Identifier: MIT\n\
*\n\
* Generated by : LDP #VERSION#\n\
*                date: %-30s\n\
*/\n\
\n"%(__generate_date())

    return header.replace("#VERSION#", _version_string())

def generate_ldp_version_header_warning():
    header="\
/**\n\
* Copyright (c) 2023 Dassault Aviation\n\
*\n\
* SPDX-License-Identifier: MIT\n\
*\n\
* Generated by : LDP #VERSION#\n\
*                date: %-30s\n\
*\n\
* WARNING: all changes made in this file will be lost\n\
*/\n\
\n"%(__generate_date())

    return header.replace("#VERSION#", _version_string())

def generate_ldp_version_header_cmake():
    header="\
#************************************************************************\n\
# Copyright (c) 2023 Dassault Aviation\n\
#\n\
# SPDX-License-Identifier: MIT\n\
#\n\
# Generated by : LDP #VERSION#\n\
#                date: %-30s #\n\
#\n\
# WARNING: all changes made in this file will be lost \n\
#*************************************************************************\n\
\n"%(__generate_date())

    return header.replace("#VERSION#", _version_string())
