/* Generated by PARSEC */
/* Module Implementation myCompFinisher_mod */

#include "ECOA.h"
#include "myCompFinisher_mod.h"

#include <stdio.h>
#include <unistd.h>
#include <signal.h>
#include <assert.h>
//#include "ldp_mod_container_util.h"

/* Entry points for lifecycle operations */
#include <stdarg.h>
static void print_log(myCompFinisher_mod__context* context, const char *format, ...){
va_list vl;
ECOA__log log;
va_start(vl, format);
vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
va_end( vl);

myCompFinisher_mod_container__log_trace(context, log);
}

void myCompFinisher_mod__INITIALIZE__received(myCompFinisher_mod__context* context)
{
  /* @TODO TODO - To be implemented */
  context->user.nb_finish=0;
}

void myCompFinisher_mod__REINITIALIZE__received(myCompFinisher_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompFinisher_mod__START__received(myCompFinisher_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompFinisher_mod__STOP__received(myCompFinisher_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompFinisher_mod__SHUTDOWN__received(myCompFinisher_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompFinisher_mod__finish_event__received(myCompFinisher_mod__context* context)
{
  context->user.nb_finish++;
  if(context->user.nb_finish == 7){
    print_log(context,"\033[1;32m SUCCESS\033[0m");
        //ldp_kill_platform((ldp_module_context*)context->platform_hook);
  }
}
