/* Generated by PARSEC */
/* Module Implementation mySender_AM */

#include "ECOA.h"
#include "mySender_AM.h"
#include <stdio.h>
#include <stdarg.h>

static void print_log(mySender_AM__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  mySender_AM_container__log_trace(context, log);
}

/* The following functions must be implemented by this module: */

/* Entrypoints for lifecycle events */
void mySender_AM__INITIALIZE__received(mySender_AM__context* context)
{
   /* One-shot initialisation activities: */
   /* @TODO TODO - To be implemented */

context->user.nb_trig=0;
}

void mySender_AM__START__received(mySender_AM__context* context)
{
   /* @TODO TODO - To be implemented */
}

void mySender_AM__STOP__received(mySender_AM__context* context)
{
   /* @TODO TODO - To be implemented */
}

void mySender_AM__SHUTDOWN__received(mySender_AM__context* context)
{
   /* @TODO TODO - To be implemented */
}

/* Entrypoints for module operations */
void
mySender_AM__Trig__received (
  mySender_AM__context* context
 )
{
   /* @TODO TODO - To be implemented */
	context->user.nb_trig++;
	//printf("Trig %i\n", context->user.nb_trig);
	if(context->user.nb_trig == 2){
		mySender_AM_container__Pong__send(context);
		context->user.nb_trig=0;
	}
}
