/* Generated by PARSEC */
/* Module User Context Header for module myFinal_AM */
#if !defined(__MYFINAL_AM_USER_CONTEXT_H__)
#define __MYFINAL_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myFinal_AM_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/
	int nb;

  /*********** USER ***********/
} myFinal_AM_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myFinal_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYFINAL_AM_USER_CONTEXT_H__ */
