/* Generated by PARSEC */
/* Module User Context Header for module myDemoPing_AM2 */
#if !defined(_MYDEMOPING_AM2_USER_CONTEXT_H)
#define _MYDEMOPING_AM2_USER_CONTEXT_H

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPing_AM2_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
    /*********** START USER-WRITTEN USER ***********/
    ECOA__uint32 current_nb;
    ECOA__uint32 pong_nb;
    ECOA__uint32 data_r_value;
    ECOA__uint32 tick_nb;
    /*********** START USER-WRITTEN USER ***********/
} myDemoPing_AM2_user_context;

#if defined(__cplusplus)
}
#endif

#endif  /* _MYDEMOPING_AM2_USER_CONTEXT_H */
