/* Generated by PARSEC */
/* Module Implementation myDemoClient_mod_impl */

#include "ECOA.h"
#include "myDemoClient_mod_impl.h"

#include "pingpong.h"
#include <assert.h>
#include <stdio.h>
#include <stdarg.h>

/* Entry points for lifecycle operations */
void myDemoClient_mod_impl__INITIALIZE__received(myDemoClient_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoClient_mod_impl__START__received(myDemoClient_mod_impl__context* context)
{
	context->user.response_num = 0;
	sleep(1);
	ECOA__uint32 comp_id;
	ECOA__uint32 mod_id;
	myDemoClient_mod_impl_container__get_comp_id_value(context, &comp_id);
	myDemoClient_mod_impl_container__get_mod_id_value(context, &mod_id);

	pingpong__T_2D_Position Ping_Position= {comp_id,mod_id};

	ECOA__uint32 Ping_Target = 12;
	ECOA__uint32 ID;


	ECOA__return_status ret;
	ret = myDemoClient_mod_impl_container__RR_ext_0_Async__request_async(context, &ID,  &Ping_Position, Ping_Target);
	assert(ret == ECOA__return_status_OK);

	Ping_Target = 13;
	ret = myDemoClient_mod_impl_container__RR_local_Async__request_async(context, &ID, &Ping_Position, Ping_Target);
	assert(ret == ECOA__return_status_OK);


	Ping_Target = 14;
	ret = myDemoClient_mod_impl_container__RR_ext_1_Async__request_async(context, &ID, &Ping_Position, Ping_Target);
	assert(ret == ECOA__return_status_OK);
}

void myDemoClient_mod_impl__STOP__received(myDemoClient_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoClient_mod_impl__SHUTDOWN__received(myDemoClient_mod_impl__context* context)
{
  /* @TODO TODO - To be implemented */
}

static void print_log(myDemoClient_mod_impl__context* context, const char *format, ...){
    va_list vl;
    ECOA__log log;

    va_start(vl, format);
    vsnprintf(log.data, ECOA__LOG_MAXSIZE, format, vl);
    va_end( vl);

  myDemoClient_mod_impl_container__log_trace(context, log);
}

static void check_response(myDemoClient_mod_impl__context* context,const ECOA__return_status status, const pingpong__T_2D_Position* Pong_Position, const ECOA__uint32 Pong_Target){
	ECOA__uint32 comp_id;
	ECOA__uint32 mod_id;
	myDemoClient_mod_impl_container__get_comp_id_value(context, &comp_id);
	myDemoClient_mod_impl_container__get_mod_id_value(context, &mod_id);

	assert(status == ECOA__return_status_OK);
	assert(Pong_Position->Latitude == comp_id);
	assert(Pong_Position->Longitude == mod_id);



}
static void send_kill_PF(myDemoClient_mod_impl__context* context){
	ECOA__uint32 mod_id;
	ECOA__uint32 comp_id;
	myDemoClient_mod_impl_container__get_comp_id_value(context, &comp_id);
	myDemoClient_mod_impl_container__get_mod_id_value(context, &mod_id);

	if(context->user.response_num ==3){
		print_log(context, "Finish comp: %i, mod : %i", comp_id, mod_id);
		myDemoClient_mod_impl_container__finish__send(context);
	}
}

void myDemoClient_mod_impl__RR_ext_0_Async__response_received(myDemoClient_mod_impl__context* context, const ECOA__uint32 ID, const ECOA__return_status status, const pingpong__T_2D_Position* Pong_Position, const ECOA__uint32 Pong_Target)
{
	check_response(context, status, Pong_Position, Pong_Target);
	assert(Pong_Target == 13);
	print_log(context, "Received answer RR extern 0\n");
	context->user.response_num++;
	send_kill_PF(context);
}

void myDemoClient_mod_impl__RR_local_Async__response_received(myDemoClient_mod_impl__context* context, const ECOA__uint32 ID, const ECOA__return_status status, const pingpong__T_2D_Position* Pong_Position, const ECOA__uint32 Pong_Target)
{
	check_response(context, status, Pong_Position, Pong_Target);
	assert(Pong_Target == 23);
	print_log(context, "Received answer RR extern local \n");
	context->user.response_num++;
	send_kill_PF(context);
}

void myDemoClient_mod_impl__RR_ext_1_Async__response_received(myDemoClient_mod_impl__context* context, const ECOA__uint32 ID, const ECOA__return_status status, const pingpong__T_2D_Position* Pong_Position, const ECOA__uint32 Pong_Target)
{
	check_response(context, status, Pong_Position, Pong_Target);
	assert(Pong_Target == 15);
	print_log(context, "Received answer RR extern 1 \n");
	context->user.response_num++;
	send_kill_PF(context);
}

