/* Generated by PARSEC */
/* Module User Context Header for module myDemoClient_AM */
#if !defined(__MYDEMOCLIENT_AM_USER_CONTEXT_H__)
#define __MYDEMOCLIENT_AM_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoClient_AM_user_context.h
 */

/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/

  /*********** USER ***********/
} myDemoClient_AM_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myDemoClient_AM_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYDEMOCLIENT_AM_USER_CONTEXT_H__ */
