/* Generated by PARSEC */
/* Module User Context Header for module myDemoPing_mod1_impl */
#if !defined(__MYDEMOPING_MOD1_IMPL_USER_CONTEXT_H__)
#define __MYDEMOPING_MOD1_IMPL_USER_CONTEXT_H__

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * @file myDemoPing_mod1_impl_user_context.h
 */

#include "pingpong.h"
/* Module User Context Structure */
typedef struct
{
  /*********** USER ***********/
int nb_ping_response;
  /*********** USER ***********/
} myDemoPing_mod1_impl_user_context;
/* Warm start Module Context structure */
typedef struct
{
   /************* START USER-WRITTEN CODE *************/

   /*************** END USER-WRITTEN CODE *************/
} myDemoPing_mod1_impl_warm_start_context;

#if defined(__cplusplus)
} 
#endif

#endif  /* __MYDEMOPING_MOD1_IMPL_USER_CONTEXT_H__ */
