/* Generated by PARSEC */
/* Module Implementation myCompWriter_mod */

#include "ECOA.h"
#include "myCompWriter_mod.h"

#include "ECOA.h"
#include "VD_lib.h"
#include <stdio.h>
#include <assert.h>
/* Entry points for lifecycle operations */
void myCompWriter_mod__INITIALIZE__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod__START__received(myCompWriter_mod__context* context)
{
	myCompWriter_mod_container__write_vector0_handle data_handle0;
	myCompWriter_mod_container__write_vector1_handle data_handle1;
	// first write
	assert(myCompWriter_mod_container__write_vector0__get_write_access(context, &data_handle0) == ECOA__return_status_DATA_NOT_INITIALIZED);
	data_handle0.data->nb_x=0;
	assert(myCompWriter_mod_container__write_vector0__publish_write_access(context, &data_handle0) == ECOA__return_status_OK);

	// first write
	assert(myCompWriter_mod_container__write_vector1__get_write_access(context, &data_handle1) == ECOA__return_status_OK);
	data_handle1.data->nb_y=0;
	assert(myCompWriter_mod_container__write_vector1__publish_write_access(context, &data_handle1) == ECOA__return_status_OK);
}

void myCompWriter_mod__STOP__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod__SHUTDOWN__received(myCompWriter_mod__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myCompWriter_mod__TriggerEvent__received(myCompWriter_mod__context* context)
{
	myCompWriter_mod_container__write_vector0_handle data_handle0;
	myCompWriter_mod_container__write_vector1_handle data_handle1;
	// first write
	assert(myCompWriter_mod_container__write_vector0__get_write_access(context, &data_handle0) == ECOA__return_status_OK);
	assert(data_handle0.data->nb_y == data_handle0.data->nb_x);
	data_handle0.data->nb_x++;
	assert(myCompWriter_mod_container__write_vector0__publish_write_access(context, &data_handle0) == ECOA__return_status_OK);

	// first write
	assert(myCompWriter_mod_container__write_vector1__get_write_access(context, &data_handle1) == ECOA__return_status_OK);
	data_handle1.data->nb_y++;
	assert(data_handle1.data->nb_y == data_handle1.data->nb_x);
	assert(myCompWriter_mod_container__write_vector1__publish_write_access(context, &data_handle1) == ECOA__return_status_OK);

}

