/* Generated by PARSEC */
/* Module Implementation myDemoFinish_AM */

#include "ECOA.h"
#include "myDemoFinish_AM.h"

#include "ECOA.h"
#include "lib_module.h"

#include "ldp_structures.h"
#include "ldp_mod_container_util.h"

/* Entry points for lifecycle operations */
void myDemoFinish_AM__INITIALIZE__received(myDemoFinish_AM__context* context)
{
  context->user.finish_count = 0x00;
}

void myDemoFinish_AM__START__received(myDemoFinish_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_AM__STOP__received(myDemoFinish_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_AM__SHUTDOWN__received(myDemoFinish_AM__context* context)
{
  /* @TODO TODO - To be implemented */
}

void myDemoFinish_AM__Finish_Received__received(myDemoFinish_AM__context* context)
{
  context->user.finish_count++;
  if (context->user.finish_count == 8){
  	sleep(1);
    ldp_kill_platform((ldp_module_context*)context->platform_hook);
  }
}
